#!/usr/bin/env python3
"""
Evidence-based PostToolUse state tracker for /tdd.
Auto-generated by /av2.

Tracks workflow progress based on EVIDENCE, not keyword matching.
A stage is complete IF AND ONLY IF evidence rules are satisfied.
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path

# Add hooks directory to path for terminal detection
hooks_dir = Path("P:/.claude/hooks")
if str(hooks_dir) not in sys.path:
    sys.path.insert(0, str(hooks_dir))

from terminal_detection import detect_terminal_id


def _get_state_file() -> Path:
    """Get terminal-isolated state file path.

    Uses home-directory based path for multi-terminal safety.
    """
    terminal_id = detect_terminal_id()
    state_dir = Path.home() / ".claude" / ".state" / "tdd" / terminal_id
    state_dir.mkdir(parents=True, exist_ok=True)
    return state_dir / "tdd_workflow.json"


EVIDENCE_RULES = {
    1: {
        "command_pattern": "pytest.*>|cat|grep|head|tail|ls",
        "exit_code": "any",
    },
    2: {
        "command_pattern": "pytest",
        "output_contains": [r"FAILED|failed|ERROR|error"],
        "exit_code": "nonzero",
    },
    3: {
        "command_pattern": "pytest",
        "output_contains": [r"passed"],
        "output_not_contains": [r"FAILED|ERROR"],
        "exit_code": "zero",
    },
    4: {
        "output_not_contains": [r"dry.?run|--dry|DRY RUN"],
        "exit_code": "zero",
    },
    5: {
        "command_pattern": r"pytest\s+tests/|pytest\s+-",
        "output_contains": [r"passed"],
        "output_not_contains": [r"FAILED"],
        "exit_code": "zero",
    },
    6: {
        "command_pattern": "pytest",
        "output_contains": [r"passed"],
        "exit_code": "zero",
    },
}

STAGE_NAMES = {
    1: "DISCOVER",
    2: "RED",
    3: "GREEN",
    4: "VERIFY",
    5: "REGRESSION",
    6: "REFACTOR",
}

MAX_STAGE = 6


def check_explicit_marker(output: str):
    """Check for explicit completion markers (highest priority)."""
    match = re.search(r"✅\s*STAGE\s*(\d+(?:\.\d+)?)\s*COMPLETE", output, re.I)
    if match:
        stage = float(match.group(1))
        return int(stage) if stage == int(stage) else stage

    for stage_num, name in STAGE_NAMES.items():
        pattern = r"✅\s*(?:PHASE\s+)?" + re.escape(name) + r"\s+COMPLETE"
        if re.search(pattern, output, re.I):
            return stage_num

    return None


def check_evidence(stage_num: int, command: str, output: str, exit_code: int) -> bool:
    """Check if evidence satisfies stage completion criteria."""
    if stage_num not in EVIDENCE_RULES:
        return False

    rule = EVIDENCE_RULES[stage_num]

    cmd_pattern = rule.get("command_pattern")
    if cmd_pattern and not re.search(cmd_pattern, command, re.I):
        return False

    for pattern in rule.get("output_contains", []):
        if not re.search(pattern, output, re.I):
            return False

    for pattern in rule.get("output_not_contains", []):
        if re.search(pattern, output, re.I):
            return False

    exit_check = rule.get("exit_code")
    if exit_check == "zero" and exit_code != 0:
        return False
    if exit_check == "nonzero" and exit_code == 0:
        return False

    return True


def read_state() -> dict:
    state_file = _get_state_file()
    if state_file.exists():
        try:
            return json.loads(state_file.read_text())
        except (OSError, json.JSONDecodeError):
            pass

    return {
        "skill": "tdd",
        "current_stage": 0,
        "max_stage": MAX_STAGE,
        "stages_completed": [],
        "halted": False,
        "halt_reason": None,
        "complete": False,
        "evidence_log": [],
        "started_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat(),
    }


def write_state(state: dict):
    state_file = _get_state_file()
    state_file.parent.mkdir(parents=True, exist_ok=True)
    state["updated_at"] = datetime.now().isoformat()
    state_file.write_text(json.dumps(state, indent=2))


def main():
    try:
        payload = json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        print(json.dumps({}))
        sys.exit(0)

    tool_name = payload.get("tool_name", "")
    if tool_name != "Bash":
        print(json.dumps({}))
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    tool_result = payload.get("tool_result", {})

    command = tool_input.get("command", "")
    output = tool_result.get("stdout", "") + tool_result.get("stderr", "")
    exit_code = tool_result.get("exitCode", 0)

    state = read_state()

    # Priority 1: Explicit marker
    completed_stage = check_explicit_marker(output)
    detection_method = "explicit_marker" if completed_stage else None

    # Priority 2: Evidence rules (check next expected stage)
    if completed_stage is None:
        next_stage = state["current_stage"] + 1
        if next_stage <= MAX_STAGE and check_evidence(next_stage, command, output, exit_code):
            completed_stage = next_stage
            detection_method = "evidence_rule"

    if completed_stage is not None:
        state["evidence_log"].append(
            {
                "stage": completed_stage,
                "method": detection_method,
                "command": command[:100],
                "exit_code": exit_code,
                "timestamp": datetime.now().isoformat(),
            }
        )

        if completed_stage not in state["stages_completed"]:
            state["stages_completed"].append(completed_stage)
        state["current_stage"] = max(state["current_stage"], completed_stage)

        if state["current_stage"] >= MAX_STAGE:
            state["complete"] = True

        write_state(state)

    if exit_code != 0 and re.search(r"CRITICAL|HIGH.*FAIL|HALT|BLOCKED", output, re.I):
        state["halted"] = True
        state["halt_reason"] = f"Failure detected (exit {exit_code})"
        write_state(state)

    print(json.dumps({}))
    sys.exit(0)


if __name__ == "__main__":
    main()
