#!/usr/bin/env python3
"""report.py — generate a pipeline report after sync, using progressive disclosure.

Design principle (from [[close-report-design-user-centric-progressive-disclosure]]):
outcome-first, detail-on-request. Level 1 is scannable in 2 seconds (did it
work? how fast? how complete?). Level 2 is drill-in detail. Level 3 is the
full data dump (only with --verbose).

Usage:
  # Auto-generated by sync.py after each successful sync
  # (sync.py calls: python report.py --notebook <id> --profile codex)

  # Manual: generate report for a synced notebook
  python report.py --notebook <uuid> --profile codex

  # Verbose (include Level 3: per-cluster breakdown, size histogram)
  python report.py --notebook <uuid> --profile codex --verbose

  # JSON output (for programmatic consumption)
  python report.py --notebook <uuid> --profile codex --json
"""
from __future__ import annotations

import argparse
import json
import re
import statistics
import subprocess
import sys
from collections import Counter
from pathlib import Path

WIKI_VAULT = Path("P:/.data/wiki")
TRANSCRIPTS_DIR = WIKI_VAULT / "sources" / "transcripts"
CONCEPTS_DIR = WIKI_VAULT / "concepts"
SYNC_MANIFEST = WIKI_VAULT / "_state" / "nlm-sync-manifest.json"


def run(cmd: list[str], timeout: int = 120) -> tuple[int, str, str]:
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, encoding="utf-8")
        return r.returncode, r.stdout or "", r.stderr or ""
    except subprocess.TimeoutExpired:
        return 124, "", f"TIMEOUT after {timeout}s"


def list_sources(notebook_id: str, profile: str) -> list[dict]:
    rc, out, _ = run(["nlm", "source", "list", notebook_id, "--profile", profile, "--json"], timeout=120)
    if rc != 0:
        return []
    try:
        data = json.loads(out)
        return data if isinstance(data, list) else data.get("sources", [])
    except json.JSONDecodeError:
        return []


def load_manifest() -> dict:
    if SYNC_MANIFEST.exists():
        try:
            return json.loads(SYNC_MANIFEST.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass
    return {"notebooks": {}}


def notebook_title(nb_id: str, profile: str) -> str:
    rc, out, _ = run(["nlm", "notebook", "get", nb_id, "--profile", profile, "--json"], timeout=60)
    if rc != 0:
        return nb_id
    try:
        return json.loads(out).get("title", nb_id)
    except json.JSONDecodeError:
        return nb_id


# --- metric collection ---------------------------------------------------

def collect_metrics(nb_id: str, profile: str, sync_result: dict | None = None) -> dict:
    """Collect all pipeline metrics for a notebook."""
    manifest = load_manifest()
    entry = manifest.get("notebooks", {}).get(nb_id, {})
    sources = list_sources(nb_id, profile)
    n_sources = len(sources) if sources else len(entry.get("source_ids", []))
    status_counts = Counter(s.get("status", "?") for s in sources) if sources else Counter()

    slugs = entry.get("concept_slugs", [])

    # Transcript files (all notebooks; filtered below)
    tx_files = list(TRANSCRIPTS_DIR.glob("*.md")) if TRANSCRIPTS_DIR.exists() else []

    # Filter to this notebook's transcripts (via frontmatter)
    nb_tx = []
    for f in tx_files:
        try:
            head = f.read_text(encoding="utf-8")[:600]
            if f"notebook_id: {nb_id}" in head:
                nb_tx.append(f)
        except (OSError, UnicodeDecodeError):
            continue
    nb_tx_ids = {f.stem for f in nb_tx}

    # Citation coverage: which transcripts are referenced in concept pages
    cited_ids = set()
    cluster_data = []
    for slug in slugs:
        p = CONCEPTS_DIR / f"{slug}.md"
        if not p.exists():
            continue
        t = p.read_text(encoding="utf-8")
        title_m = re.search(r'title:\s*"([^"]+)"', t)
        title = title_m.group(1) if title_m else slug
        members = set(re.findall(r'NotebookLM source ([a-f0-9-]{36})', t))
        cited_ids.update(members)
        n_claims = t.count("- **Claim:**")
        cluster_data.append({
            "slug": slug, "title": title,
            "member_count": len(members),
            "citation_count": n_claims,
        })

    cited_in_nb = cited_ids & nb_tx_ids
    citation_rate = len(cited_in_nb) / len(nb_tx_ids) * 100 if nb_tx_ids else 0

    # Transcript size distribution
    sizes = []
    for f in nb_tx:
        t = f.read_text(encoding="utf-8")
        i = t.find("---", 3)
        body = t[i + 3:].strip() if i > 0 else t
        # Strip leading "# Title" line
        body = re.sub(r"^#\s+.*\n", "", body, count=1)
        sizes.append(len(body.split()))
    sizes.sort()

    # Timing (from sync_result if provided)
    duration_s = sync_result.get("duration_s") if sync_result else None
    vph = None
    if duration_s and n_sources:
        vph = (n_sources / duration_s) * 3600

    return {
        "notebook_id": nb_id,
        "notebook_title": entry.get("title") or notebook_title(nb_id, profile),
        "n_sources": n_sources,
        "n_transcripts": len(nb_tx_ids),
        "n_unrecoverable": status_counts.get(3, 0),
        "n_concept_pages": len(slugs),
        "n_pages_validated": len([s for s in slugs if (CONCEPTS_DIR / f"{s}.md").exists()]),
        "citation_rate": round(citation_rate, 1),
        "cited_count": len(cited_in_nb),
        "uncited_count": len(nb_tx_ids) - len(cited_in_nb),
        "total_citations": sum(c["citation_count"] for c in cluster_data),
        "avg_citations_per_page": round(sum(c["citation_count"] for c in cluster_data) / len(cluster_data), 1) if cluster_data else 0,
        "duration_s": duration_s,
        "videos_per_hour": round(vph) if vph else None,
        "cluster_data": cluster_data,
        "transcript_sizes": {
            "min": min(sizes) if sizes else 0,
            "max": max(sizes) if sizes else 0,
            "median": int(statistics.median(sizes)) if sizes else 0,
            "waste": sum(1 for s in sizes if s < 50),
            "thin": sum(1 for s in sizes if s < 200),
            "long": sum(1 for s in sizes if s > 5000),
            "raw": sizes,
        } if sizes else None,
        "last_synced": entry.get("last_synced_at", "—"),
        "pipeline": entry.get("pipeline", "—"),
    }


# --- visual helpers (pure Unicode, zero dependencies) -------------------

SPARK_BLOCKS = "▁▂▃▄▅▆▇█"
BAR_BLOCK = "█"
BAR_LIGHT = "░"


def sparkline(values: list[int], bins: int = 16) -> str:
    """Render a Unicode sparkline histogram from a list of values."""
    if not values:
        return ""
    lo, hi = min(values), max(values)
    if hi == lo:
        return SPARK_BLOCKS[3] * min(len(values), bins)
    bucket_size = (hi - lo) / bins
    counts = [0] * bins
    for v in values:
        idx = min(int((v - lo) / bucket_size), bins - 1)
        counts[idx] += 1
    max_c = max(counts) if counts else 1
    return "".join(SPARK_BLOCKS[min(int(c / max_c * 7), 7)] if c > 0 else " " for c in counts)


def bar_chart(value: int, max_val: int, width: int = 24) -> str:
    """Render a horizontal Unicode bar: ████████████████░░░░░░░░"""
    if max_val == 0:
        return BAR_LIGHT * width
    filled = int(value / max_val * width)
    return BAR_BLOCK * filled + BAR_LIGHT * (width - filled)


def file_link(slug: str) -> str:
    """Render a clickable file:/// URI for a concept page slug."""
    return f"file:///P:/.data/wiki/concepts/{slug}.md"


# --- report rendering (progressive disclosure) ---------------------------

def render_report(m: dict, verbose: bool = False) -> str:
    """Render metrics as a progressive-disclosure report.

    Level 1: outcome summary (4 lines, scannable in 2s)
    Level 2: drill-in detail (cluster bar chart, sparkline, coverage)
    Level 3: full data (verbose flag: per-cluster detail with clickable links)
    """
    lines = []

    # === LEVEL 1: outcome summary ===
    lines.append("=" * 60)
    lines.append(f"SYNC REPORT: {m['notebook_title']}")
    lines.append("=" * 60)
    lines.append("")

    export_rate = (m["n_transcripts"] / m["n_sources"] * 100) if m["n_sources"] else 0
    validation_rate = (m["n_pages_validated"] / m["n_concept_pages"] * 100) if m["n_concept_pages"] else 0

    # One-line outcome
    if validation_rate == 100 and export_rate > 95:
        status = "✅ SUCCESS"
    elif validation_rate >= 80:
        status = "⚠️ PARTIAL"
    else:
        status = "❌ FAILED"
    lines.append(f"  {status}  {m['n_transcripts']}/{m['n_sources']} transcripts "
                 f"({export_rate:.0f}%) → {m['n_concept_pages']} pages "
                 f"({validation_rate:.0f}% validated)")

    if m["videos_per_hour"]:
        lines.append(f"  Throughput: {m['videos_per_hour']:,} videos/hour"
                     f"  ({m['duration_s']:.0f}s total)")
    lines.append(f"  Citation coverage: {m['citation_rate']:.0f}%  "
                 f"({m['cited_count']}/{m['n_transcripts']} transcripts cited)")
    lines.append(f"  Avg citations/page: {m['avg_citations_per_page']}")
    if m["n_unrecoverable"]:
        lines.append(f"  Unrecoverable: {m['n_unrecoverable']} source(s)")
    lines.append("")

    if not verbose:
        lines.append("  (Run with --verbose for cluster bar chart and size sparkline)")
        return "\n".join(lines)

    # === LEVEL 2: cluster distribution (ASCII bar chart) ===
    lines.append("-" * 60)
    lines.append("CLUSTER DISTRIBUTION")
    lines.append("-" * 60)
    sorted_clusters = sorted(m["cluster_data"], key=lambda x: -x["member_count"])
    max_members = max((c["member_count"] for c in sorted_clusters), default=1)
    for c in sorted_clusters:
        bar = bar_chart(c["member_count"], max_members)
        lines.append(f"  {bar} {c['member_count']:>3}  {c['citation_count']:>3} cites  {c['title']}")
    # Balance indicator
    if sorted_clusters:
        max_c = max(c["member_count"] for c in sorted_clusters)
        min_c = min(c["member_count"] for c in sorted_clusters)
        ratio = max_c / min_c if min_c else float("inf")
        lines.append("")
        if ratio > 10:
            lines.append(f"  ⚠ Cluster balance: {ratio:.0f}x ratio (max {max_c} / min {min_c}) — "
                         f"consider raising --max-subtopics")
        else:
            lines.append(f"  Cluster balance: {ratio:.1f}x ratio (healthy)")
    lines.append("")

    # === LEVEL 2: transcript size distribution (sparkline) ===
    if m["transcript_sizes"]:
        ts = m["transcript_sizes"]
        lines.append("-" * 60)
        lines.append("TRANSCRIPT SIZE DISTRIBUTION")
        lines.append("-" * 60)
        lines.append(f"  {sparkline(_get_raw_sizes(m))}")
        lines.append(f"  Min: {ts['min']} words   Max: {ts['max']} words   "
                     f"Median: {ts['median']} words")
        lines.append(f"  <50 words (waste): {ts['waste']}   "
                     f"<200 (thin): {ts['thin']}   "
                     f">5000 (long): {ts['long']}")
        lines.append("")

    # === LEVEL 3: per-cluster detail with clickable links ===
    lines.append("-" * 60)
    lines.append("PER-CLUSTER DETAIL (click slug to open)")
    lines.append("-" * 60)
    for c in sorted_clusters:
        lines.append(f"  {c['title']}")
        lines.append(f"    {file_link(c['slug'])}")
        lines.append(f"    members: {c['member_count']}  citations: {c['citation_count']}")
        lines.append("")

    return "\n".join(lines)


def _get_raw_sizes(m: dict) -> list[int]:
    """Extract raw word counts for sparkline from metrics."""
    ts = m.get("transcript_sizes")
    if not ts:
        return []
    return ts.get("raw", [])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--notebook", required=True)
    ap.add_argument("--profile", default="codex")
    ap.add_argument("--verbose", action="store_true", help="include Level 3 detail")
    ap.add_argument("--json", action="store_true", help="output as JSON instead of text")
    ap.add_argument("--sync-result", default=None, help="JSON sync result (from sync.py)")
    ap.add_argument("--duration", type=float, default=None, help="sync duration in seconds")
    args = ap.parse_args()

    sync_result = None
    if args.sync_result:
        sync_result = json.loads(args.sync_result)
    elif args.duration:
        sync_result = {"duration_s": args.duration}

    m = collect_metrics(args.notebook, args.profile, sync_result)

    if args.json:
        print(json.dumps(m, ensure_ascii=False, indent=2))
    else:
        print(render_report(m, verbose=args.verbose))
    return 0


if __name__ == "__main__":
    sys.exit(main())
