#!/usr/bin/env python3
"""
PreToolUse gate for /refactor skill.
Blocks tools not allowed in the current workflow phase.
Auto-generated by /av improve /refactor
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from state_manager_refactor import read_state

def main():
    input_data = json.loads(sys.stdin.read())
    tool_name = input_data.get("tool_name", "")

    state = read_state()
    if not state:
        # No active state - allow all tools (skill not in progress or state expired)
        sys.exit(0)

    allowed = state.get("allowed_tools", [])
    phase = state.get("phase", "unknown")

    if tool_name not in allowed:
        print(f"⛔ /refactor [{phase}]: '{tool_name}' not allowed. Allowed: {allowed}", file=sys.stderr)
        sys.exit(2)  # Block the tool

    sys.exit(0)  # Allow

if __name__ == "__main__":
    main()