[paths]
channels_base = "E:/dnld_media/telegram/channels"

[telegram]
api_id = 20467910
api_hash = "ae17ebdb304f5de5752480b820e8c501"
session_string = "1AZWarzYBuwMFLJoun1z5am7kHhcQucHEYlnOmJFc0svVs0DjxHEmSXx3ZCf2iF6TI54Q5f94h4LCTTjN6sVes8msZDWnlxWOia016u67_SnUF22O_5bpkTz5p4e-SD4z14s98iaSjOjNpQbe5cI5ZfuY4LxAz_oeTzyQwUMuh9YMqh-AbA3LSXIXz29ZkAC_6e7_8CLwaB7bgRaXwmGoBHdKJPDKkztzW7eq1gBqxxpZfqM36rhzr3s8YpLTdu02P5kHOPH2y-PUoPmeyvqxobnXAt6JLt62ykAYt4SngoVonF3fWzl4C1GOgdOK38ADXIcZtESy5voXtztOxnbxaakWRE6IlMw="
