from pathlib import Path

plan_path = Path("P:/.claude/hooks/plans/plan-20260314-verification-claim-grounding.md")

sections = []
sections.append("# Implementation Plan: Verification Claim Grounding Subsystem")
sections.append("**Date**: 2026-03-14")
sections.append("**Status**: DRAFT")
sections.append("**Priority**: HIGH (Reliability + Safety)")
sections.append("")
sections.append("---")
sections.append("")
sections.append("## Problem Statement")
sections.append("")
sections.append("The Claude Code hook system fails to distinguish between a tool being used this turn and a claim being grounded in that tool output. The AI states hypotheses as confirmed facts without verifying the specific entities being claimed about. The result is destructive recommendations based on unverified conclusions.")
sections.append("")
sections.append("Two concrete failure modes observed:")
sections.append("1. AI sees broken junction target, asserts Package has no skill/ directory without checking, recommends Remove-Item. The skill existed at a different path.")
sections.append("2. AI performs ritual self-correction (COG framework output) without verifying before acting again.")
sections.append("")
sections.append("Root cause: Hooks check was any verification tool used this turn - a coarse binary signal. Required: does tool output from this turn reference the specific entity being claimed about.")
sections.append("")
sections.append("---")
sections.append("")
sections.append("## Context Analysis")
sections.append("")
sections.append("Verified from code inspection:")
sections.append("")
sections.append("evidence_store.py: SQLite-backed tool event store. Schema includes terminal_id column in tool_events table. terminal_id IS written by PostToolUse router. load_tool_events() filters by session_id only - terminal_id NOT used as filter. Confirmed cross-terminal contamination gap.")
sections.append("")
sections.append("state/turn_markers/: Per-terminal turn marker files keyed turn_start_{session_id}__{terminal_id}.json. All observed values show turn_start_event_id: 0 - turn scoping not functioning correctly.")
sections.append("")
sections.append("Stop_router.py: Routes Stop hooks in-process via ACTIVE_RUNTIME_HOOKS.")
sections.append("")
sections.append("Existing Stop hooks: Stop_negative_existence_guard checks any-tool-used, Stop_unverified_existence_gate checks external URLs, StopHook_unverified_stance catches sycophancy patterns.")
sections.append("")
sections.append("anti_sycophancy/overconfidence_detector.py: Catches causal assertions and catastrophizing. NOT wired into Stop router.")
sections.append("")
sections.append("Multi-terminal failure confirmed: load_tool_events(session_id) returns events from all terminals sharing that session.")
sections.append("")
sections.append("Turn scoping failure confirmed: All turn marker files show turn_start_event_id: 0.")
sections.append("")
sections.append("---")
sections.append("")
sections.append("## Existing Implementation Discovery")
sections.append("")
sections.append("evidence_store.py load_tool_events(): filters by session_id only. Gap: no terminal_id filter.")
sections.append("evidence_store.py append_tool_event(): correctly accepts and stores terminal_id. No gap.")
sections.append("PostToolUse_router.py: Writes tool events with terminal_id. No gap.")
sections.append("state/turn_markers/*.json: turn_start_event_id always 0. Gap: writer not setting correct value.")
sections.append("Stop_negative_existence_guard.py: checks any tool used this turn. Gap: too coarse.")
sections.append("Stop_unverified_existence_gate.py: checks external resource claims. Gap: no entity-level matching.")
sections.append("StopHook_unverified_stance.py: catches sycophancy/empty-hedge patterns. Gap: misses hypothesis-as-fact pattern.")
sections.append("anti_sycophancy/overconfidence_detector.py: Not wired into Stop router. Gap: dead module.")
sections.append("Stop_router.py ACTIVE_RUNTIME_HOOKS: Missing new gate.")
sections.append(".claude/settings.json: Missing HYPOTHESIS_AS_FACT_GATE_ENABLED and HYPOTHESIS_AS_FACT_GATE_MODE.")
sections.append("")
sections.append("---")
sections.append("")
sections.append("## Test Discovery")
sections.append("")
sections.append("Existing tests to preserve: tests/test_assumption_audit.py, tests/test_constitutional_enforcer.py, tests/test_hook_execution.py.")
sections.append("")
sections.append("New test files required:")
sections.append("- tests/test_hypothesis_as_fact_detector.py")
sections.append("- tests/test_Stop_hypothesis_as_fact_gate.py")
sections.append("- tests/test_verification_claims.py")
sections.append("- tests/test_verification_engine.py")
sections.append("- tests/test_verification_isolation.py")
sections.append("- tests/test_verification_config_reload.py")
sections.append("")
sections.append("---")
sections.append("")
sections.append("## Proposed Solution")
sections.append("")
sections.append("A phased evolution over existing infrastructure. No new receipt format, no new PostToolUse hooks, no new state directories.")
sections.append("")
sections.append("Phase 1: Fix evidence filtering gap and add new Stop gate for hypothesis-as-fact claims. No refactoring of existing hooks.")
sections.append("Phase 2: Promote detector to shared verification/ substrate. Migrate existing hooks. Fix turn scoping.")
sections.append("Phase 3: Tests, observability, feature flags, rollback documentation.")
sections.append("")
sections.append("Key design decisions:")
sections.append("- Terminal isolation via AND terminal_id in SQL query. One-line change, no schema migration.")
sections.append("- Turn scoping via existing turn markers once writer is fixed. Feature-flagged off by default.")
sections.append("- Phase 1 entity matching: path/filesystem entities only. Phase 2 expands.")
sections.append("")
sections.append("---")
sections.append("")
sections.append("## Implementation Plan")
sections.append("")
sections.append("### Phase 1: Evidence Filtering + New Gate")
sections.append("")
sections.append("**PH1-T1**: Add load_tool_events_for_context to evidence_store.py")
sections.append("- File: evidence_store.py")
sections.append("- Action: New function with terminal_id AND session_id filter; return empty list if terminal_id empty (fail-safe); reuse existing ordering and limits")
sections.append("- Points: 2")
sections.append("- Acceptance: Two terminals same session return only their own events; missing terminal_id returns empty list")
sections.append("- Prerequisites: None")
sections.append("")
sections.append("**PH1-T2**: Verify and document terminal_id write path")
sections.append("- File: evidence_store.py, PostToolUse_router.py")
sections.append("- Action: Confirm terminal_id reaches DB row (verified via code review); add integration test")
sections.append("- Points: 1")
sections.append("- Acceptance: Integration test confirms terminal_id stored in tool_events row")
sections.append("- Prerequisites: PH1-T1")
sections.append("")
sections.append("**PH1-T3**: Implement hypothesis_as_fact_detector module")
sections.append("- File: anti_sycophancy/hypothesis_as_fact_detector.py (new), tests/test_hypothesis_as_fact_detector.py (new)")
sections.append("- Action: RawClaim dataclass with text, subject_entity, claim_type, confidence, has_hedge, risk_domain; detect_claims(response_text) returning list of RawClaim; entity claim patterns, rule claim patterns, epistemic hedge detection")
sections.append("- Points: 5")
sections.append("- Acceptance: Detects broken-junction-style sentences; detects rule assertions; correctly sets has_hedge for hedged and unhedged variants")
sections.append("- Prerequisites: None")
sections.append("")
sections.append("**PH1-T4**: Implement Stop_hypothesis_as_fact_gate.py")
sections.append("- File: Stop_hypothesis_as_fact_gate.py (new), tests/test_Stop_hypothesis_as_fact_gate.py (new)")
sections.append("- Action: run(data) entrypoint; extract session_id, terminal_id, response_text; call detect_claims; call load_tool_events_for_context; entity matching; warn or block per mode; log every decision with claim text and tool events considered")
sections.append("- Points: 5")
sections.append("- Acceptance: Blocks ungrounded confident claims; allows hedged claims without evidence; allows confident claims grounded in tool events; respects HYPOTHESIS_AS_FACT_GATE_ENABLED and HYPOTHESIS_AS_FACT_GATE_MODE")
sections.append("- Prerequisites: PH1-T1, PH1-T3")
sections.append("")
sections.append("**PH1-T5**: Wire into Stop_router.py and settings.json")
sections.append("- File: Stop_router.py, .claude/settings.json")
sections.append("- Action: Add to HOOK_SEQUENCE before Stop_negative_existence_guard; add to ACTIVE_RUNTIME_HOOKS; add HYPOTHESIS_AS_FACT_GATE_ENABLED=true and HYPOTHESIS_AS_FACT_GATE_MODE=warn to settings.json")
sections.append("- Points: 2")
sections.append("- Acceptance: Hook fires in Stop sequence; toggling env var disables without code change")
sections.append("- Prerequisites: PH1-T4")
sections.append("")
sections.append("**PH1-T6**: Investigate turn_start_event_id = 0")
sections.append("- File: Turn marker writer code (to be identified)")
sections.append("- Action: Find why all turn markers show event_id 0; document findings; propose fix; no production change in Phase 1")
sections.append("- Points: 3")
sections.append("- Acceptance: Root cause documented; fix approach specified and reviewed")
sections.append("- Prerequisites: None")
sections.append("")
sections.append("### Phase 2: Shared Verification Engine + Hook Migration")
sections.append("")
sections.append("**PH2-T1**: Create verification/claims.py")
sections.append("- File: verification/claims.py (new), anti_sycophancy/hypothesis_as_fact_detector.py (refactor to wrapper)")
sections.append("- Action: Claim dataclass with id, text, targets, type, confidence, risk_domain, has_hedge; extract_claims(response_text) returning list of Claim")
sections.append("- Points: 3")
sections.append("- Acceptance: PH1 tests pass using new Claim type; detector delegates to claims module")
sections.append("- Prerequisites: PH1-T3")
sections.append("")
sections.append("**PH2-T2**: Implement verification/engine.py")
sections.append("- File: verification/engine.py (new), tests/test_verification_engine.py (new)")
sections.append("- Action: ToolEventView wrapper over evidence_store events with normalized target and facts; build_verdicts returning list of VerificationVerdict; match_claim_to_events returning SUPPORTED, REFUTED, or SILENT")
sections.append("- Points: 8")
sections.append("- Acceptance: Supported absence claims with matching ls or glob output; silent claims for unrelated paths; rule claims require Read or Glob of relevant file")
sections.append("- Prerequisites: PH2-T1, PH1-T1")
sections.append("")
sections.append("**PH2-T3**: Refactor Stop_hypothesis_as_fact_gate to use engine")
sections.append("- File: Stop_hypothesis_as_fact_gate.py")
sections.append("- Action: Replace RawClaim and string matching with verification.claims and verification.engine; policy from VerificationVerdict; env flags unchanged")
sections.append("- Points: 3")
sections.append("- Acceptance: Existing gate tests pass; engine verdicts drive policy decisions")
sections.append("- Prerequisites: PH2-T2")
sections.append("")
sections.append("**PH2-T4**: Migrate Stop_negative_existence_guard to engine")
sections.append("- File: Stop_negative_existence_guard.py, tests/test_Stop_negative_existence_guard.py")
sections.append("- Action: Replace any-tool-used heuristic with ABSENCE Claims and engine verdicts; block or warn when SILENT or REFUTED for FS_CRITICAL domain; preserve existing env flags")
sections.append("- Points: 5")
sections.append("- Acceptance: Broken-junction pattern caught by this hook; existing tests pass or updated; env flags unchanged")
sections.append("- Prerequisites: PH2-T2, PH2-T3")
sections.append("")
sections.append("**PH2-T5**: Migrate Stop_unverified_existence_gate to engine")
sections.append("- File: Stop_unverified_existence_gate.py")
sections.append("- Action: EXTERNAL domain Claims and engine verdicts requiring actual web or git fetch")
sections.append("- Points: 3")
sections.append("- Acceptance: Behavior equivalent or improved; tests for unverified URL and repo claims pass")
sections.append("- Prerequisites: PH2-T2")
sections.append("")
sections.append("**PH2-T6**: Migrate StopHook_unverified_stance to engine")
sections.append("- File: StopHook_unverified_stance.py")
sections.append("- Action: Model stance as Claim objects; use engine for grounding check; preserve current detection behavior")
sections.append("- Points: 5")
sections.append("- Acceptance: Current sycophancy scenarios still detected; stance grounding via engine")
sections.append("- Prerequisites: PH2-T2")
sections.append("")
sections.append("**PH2-T7**: Fix turn scoping in load_tool_events_for_context")
sections.append("- File: evidence_store.py, turn marker writer")
sections.append("- Action: Fix turn_start_event_id writer; add id > turn_start filter when marker available; feature flag VERIFICATION_USE_TURN_SCOPING defaulting false")
sections.append("- Points: 5")
sections.append("- Acceptance: Turn marker shows non-zero event_id; context query returns only current-turn events when flag enabled; flag off preserves Phase 1 behavior")
sections.append("- Prerequisites: PH1-T6, PH1-T1")
sections.append("")
sections.append("### Phase 3: Tests, Observability, Feature Flags")
sections.append("")
sections.append("**PH3-T1**: Multi-terminal isolation integration tests")
sections.append("- File: tests/test_verification_isolation.py (new)")
sections.append("- Action: Simulate two terminals t1 and t2 sharing session_id but different terminal_id; write tool events for t1 only; run Stop cycle for t2 with confident claim about same path; assert t2 blocked or warned; assert t1 passes")
sections.append("- Points: 3")
sections.append("- Acceptance: t2 blocked or warned despite t1 having relevant tool events; t1 passes with its own events")
sections.append("- Prerequisites: PH1-T1, PH1-T4")
sections.append("")
sections.append("**PH3-T2**: Config reload behavior tests")
sections.append("- File: tests/test_verification_config_reload.py (new)")
sections.append("- Action: Simulate env or policy change between turns; verify next Stop invocation reflects new mode without restart")
sections.append("- Points: 2")
sections.append("- Acceptance: Mode change from warn to block takes effect on next turn")
sections.append("- Prerequisites: PH1-T4, PH1-T5, PH2-T2")
sections.append("")
sections.append("**PH3-T3**: Per-terminal verification logging")
sections.append("- File: Stop_hypothesis_as_fact_gate.py or shared log module")
sections.append("- Action: Structured JSONL log per block or warn containing session_id, terminal_id, claim_id, claim_text, support_status, policy_outcome, tool event IDs considered")
sections.append("- Points: 2")
sections.append("- Acceptance: Log entries parseable as JSONL; all required fields present; one entry per decision")
sections.append("- Prerequisites: PH1-T4, PH2-T3")
sections.append("")
sections.append("**PH3-T4**: Feature flags and rollback documentation")
sections.append("- File: .claude/settings.json, docs/verification-hooks.md (new)")
sections.append("- Action: Document all env vars with defaults and descriptions; document rollback procedure; confirm conservative defaults in settings.json")
sections.append("- Points: 1")
sections.append("- Acceptance: Rollback procedure verified; all flags documented with defaults")
sections.append("- Prerequisites: PH1-T5, PH2-T3, PH2-T4, PH2-T5, PH2-T6, PH2-T7")
sections.append("")
sections.append("---")
sections.append("")
sections.append("## Risks, Success Criteria, Dependencies")
sections.append("")
sections.append("### Risks")
sections.append("1. Turn marker writer broken in non-obvious way - fixing may change session-wide event scoping for existing hooks. Mitigation: feature-flag VERIFICATION_USE_TURN_SCOPING defaults off until tested.")
sections.append("2. False positive rate from claim detection - overly aggressive patterns block legitimate confident statements. Mitigation: start in warn mode; tune from logs before switching to block.")
sections.append("3. Claim entity matching brittle for non-path entities. Mitigation: Phase 1 covers path and filesystem entities only; Phase 2 expands.")
sections.append("")
sections.append("### Success Criteria")
sections.append("- Two terminals sharing a session: t1 events do NOT satisfy t2 verification checks")
sections.append("- Package has no skill/ directory without Read or Glob of that path triggers warn or block")
sections.append("- Per documentation X does not need Y without Read of that doc triggers warn or block")
sections.append("- Hedged claims pass without intervention")
sections.append("- Claims with matching entity in tool output pass")
sections.append("- Stop_router.py latency overhead under 20ms additional per turn")
sections.append("")
sections.append("### Dependencies")
sections.append("- CLAUDE_TERMINAL_ID must be set per process. Already in place via SessionStart_terminal_id.py.")
sections.append("- evidence_store.py schema already has terminal_id column. No migration needed.")
sections.append("- Existing hook env-flag rollback pattern must be preserved for all refactored hooks.")
sections.append("- PH1-T6 findings must be reviewed before PH2-T7 implementation begins.")

plan_path.write_text("\n".join(sections), encoding="utf-8")
print(f"Written: {plan_path}")
print(f"Size: {plan_path.stat().st_size} bytes")
