
import json

# Metadata
META = {
    "strategy": {"label": "Strategy Branch", "icon": "compass", "color": "indigo"},
    "execution": {"label": "Execution Branch", "icon": "hammer", "color": "blue"},
    "quality": {"label": "Quality Branch", "icon": "shield-check", "color": "emerald"},
    "evolution": {"label": "Evolution Branch", "icon": "refresh-ccw", "color": "amber"},
    "control": {"label": "Control Branch", "icon": "cpu", "color": "rose"},
}

# Refined Structure
STRUCTURE = {
    "strategy": {
        "Initialization/Setup": [
            "/init", "/session", "/llm_models", "/health-monitor", "/telemetry", 
            "/context_status", "/library-first", "/deps", "/pwsh", "/q"
        ],
        "Planning/Analysis": [
            "/problem-statement", "/value", "/discover", "/research", "/analytics", 
            "/memory", "/task", "/triage", "/search", "/docs", "/reports", "/wo_advisory"
        ],
        "Design": [
            "/arch", "/acef", "/csaf", "/cognitive", "/constitutional-patterns", 
            "/prd", "/specify", "/workflow", "/design", "/ddd", "/orchestrate"
        ]
    },
    "execution": {
        "Development": [
            "/build", "/code-python-2025", "/code-typescript-2025", "/refactor", 
            "/tdd", "/subagent-first", "/multi-file-refactor", "/command_create", 
            "/command-enhance", "/doc_to_skill", "/ai_distiller", "/complexity", 
            "/exec", "/execution-clarity", "/web-artifacts-builder", "/sar-inst"
        ],
        "Git & VCS": [
            "/git", "/commit", "/push", "/git-safety", "/git-worktrees", 
            "/git-conventional-commits", "/git-sapling"
        ],
        "Utilities": [
            "/deps", "/write-file", "/llm_health", "/checkpoint", "/ask", 
            "/quota", "/perf", "/bgkill", "/data_processor", "/context_status",
            "/checkpoint_list", "/checkpoint_restore", "/checkpoint_diff", "/checkpoint_delete"
        ]
    },
    "quality": {
        "Testing": [
            "/test", "/tdd-cycle", "/qa", "/test-bisect", "/testing-skills"
        ],
        "Debugging & Analysis": [
            "/debug", "/analyze", "/rca", "/obs", "/investigate", "/nse", 
            "/session-transcript-w1t2", "/apply_safety_patterns", "/llm_debate"
        ],
        "Review": [
            "/comply", "/standards", "/prrp", "/truth", "/slc", 
            "/llm_doc_review", "/validate_spec", "/validate-safety-patterns"
        ]
    },
    "evolution": {
        "Evolution Branch": [ # Consolidated as requested: "Evolution Branch: learn, clean up..."
            "/learn", "/reflect", "/retro", "/cleanup", "/evolve", 
            "/update_state", "/r", "/sp", "/skills_migrate", "/value-maximization"
        ]
    },
    "control": {
        "Control Branch": [ # Consolidated as "Control Branch: steer workflows..."
           "/workflow", "/orchestrate", "/task", "/tm", "/cb", 
           "/constraints", "/hooks-edit", "/artifact", 
           "/artifact-add", "/artifact_audit", "/artifact_done",
           "/cgate", "/quadlet", "/step_6_5", "/flow", "/sap", "/sap_commit",
           "/consult", "/llm_edit_coordination", "/main", "/search_more",
           "/clear_notifications", "/clear_restore", "/restore", "/cwo", "/cwo_orchestrator"
        ]
    }
}

# Generate the JS object
data = {}

for branch, categories in STRUCTURE.items():
    meta = META[branch]
    
    # Flatten items for bullets and skills
    all_items = []
    for cat_items in categories.values():
        all_items.extend(cat_items)
    
    # Deduplicate
    all_items = sorted(list(set(all_items)))
    
    # Skills (remove leading /)
    skills = [item.lstrip('/') for item in all_items]
    
    data[branch] = {
        "label": meta["label"],
        "icon": meta["icon"],
        "color": meta["color"],
        "commands": [],
        "categories": categories,
        "bullets": all_items,
        "skills": skills,
        "agents": []
    }

# Write to file
# We'll read the existing file first to check headers, but generally we can just overwrite
js_content = "window.TECH_DATA = " + json.dumps(data, indent=4) + ";"

with open(r"P:/.claude/docs/sdlc_tech_tree/data/tech_data.js", "w", encoding="utf-8") as f:
    f.write("// Auto-generated by refine_tech_data.py\n")
    f.write(js_content)

print("Refined tech_data.js")
