# Test env vars after sourcing cc-bf
Set-Location 'P:\.claude\provider-configs'
. .\cc-bifrost.ps1

Write-Host "ANTHROPIC_BASE_URL=$env:ANTHROPIC_BASE_URL"
Write-Host "ANTHROPIC_DEFAULT_OPUS_MODEL=$env:ANTHROPIC_DEFAULT_OPUS_MODEL"
Write-Host "ANTHROPIC_DEFAULT_OPUS_MODEL_NAME=$env:ANTHROPIC_DEFAULT_OPUS_MODEL_NAME"
Write-Host "ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION=$env:ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION"
Write-Host "ANTHROPIC_API_KEY=$env:ANTHROPIC_API_KEY"