"""HyDE (Hypothetical Document Embeddings) - Simple Wrapper.

This module provides a simple data structure for HyDE documents.
The actual generation is done by Claude Code (the orchestrator)
before invoking the Python CLI.

ARCHITECTURE:
- Claude generates hypothetical documents directly (no external API calls)
- Python code just stores and uses the pre-generated document
- This avoids external LLM dependencies and API complexity
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class HypotheticalDocument:
    """Represents a hypothetical document generated by HyDE.

    The document is generated by Claude Code (the orchestrator)
    before invoking the Python CLI, not by external LLM APIs.
    """
    query: str
    content: str
    generation_model: str = "claude-code-orchestrator"
    generation_time: float = 0.0
    word_count: int = 0
    token_count: int = 0
    perspective: str = "default"  # For multi-perspective HyDE support

    def __repr__(self):
        return f"HypotheticalDocument(query='{self.query[:30]}...', words={self.word_count})"


@dataclass
class HyDEConfig:
    """Configuration for HyDE generation."""
    model: str = "claude-code-orchestrator"
    max_tokens: int = 2000
    temperature: float = 0.7
    timeout: int = 30


def _count_words(text: str) -> int:
    """Count words in text."""
    return len(text.split())


def _count_tokens(text: str) -> int:
    """Estimate token count (rough approximation: ~4 chars per token)."""
    return len(text) // 4


def create_hypothetical_document(
    query: str,
    content: str,
    config: HyDEConfig | None = None
) -> HypotheticalDocument:
    """Create a HypotheticalDocument from pre-generated content.

    The content should be generated by Claude Code before invoking
    the Python CLI. This function just wraps it in the data structure.

    Args:
        query: The original search query
        content: The pre-generated hypothetical document content
        config: Optional HyDE configuration

    Returns:
        HypotheticalDocument with metadata

    Raises:
        ValueError: If query or content is empty
        TypeError: If query or content is not a string
    """
    # Validate input
    if query is None:
        raise TypeError("Query cannot be None")
    if not isinstance(query, str):
        raise TypeError(f"Query must be a string, got {type(query)}")
    if not query or query.strip() == "":
        raise ValueError("Query cannot be empty")

    if content is None:
        raise TypeError("Content cannot be None")
    if not isinstance(content, str):
        raise TypeError(f"Content must be a string, got {type(content)}")
    if not content or content.strip() == "":
        raise ValueError("Content cannot be empty")

    # Use default config if not provided
    if config is None:
        config = HyDEConfig()

    # Calculate statistics
    word_count = _count_words(content)
    token_count = _count_tokens(content)

    return HypotheticalDocument(
        query=query,
        content=content,
        generation_model=config.model,
        generation_time=0.0,  # Time tracking happens in orchestrator
        word_count=word_count,
        token_count=token_count,
    )


# Legacy function name for compatibility - maps to new simple version
def generate_hypothetical_document(
    query: str,
    content: str | None = None,
    config: HyDEConfig | None = None
) -> HypotheticalDocument:
    """Legacy wrapper for create_hypothetical_document.

    DEPRECATED: Use create_hypothetical_document(query, content) instead.

    The 'content' parameter is now required - HyDE documents should be
    generated by Claude Code before invoking the Python CLI.

    Args:
        query: The original search query
        content: The pre-generated hypothetical document content (REQUIRED)
        config: Optional HyDE configuration

    Returns:
        HypotheticalDocument with metadata

    Raises:
        TypeError: If query is None
        ValueError: If content is None (we don't generate documents anymore)
    """
    if query is None:
        raise TypeError("Query cannot be None")

    if content is None:
        raise ValueError(
            "HyDE content must be provided. "
            "Generate the hypothetical document in Claude Code before invoking the CLI. "
            "Use create_hypothetical_document(query, content) instead."
        )

    return create_hypothetical_document(query, content, config)
