#!/usr/bin/env python3
"""
PreToolUse gate for /main-hooks skill.

Validates that Bash commands call system_health.py when /main-hooks skill is active.
Blocks incorrect Bash commands and provides helpful usage guidance.

Auto-generated by /av improve /main
"""
import json
import sys


def main() -> None:
    """Hook entry point: validate Bash commands call system_health.py."""
    try:
        input_data = json.loads(sys.stdin.read())
    except (json.JSONDecodeError, ValueError):
        # Empty stdin in PostToolUse context - pass through
        sys.exit(0)
    tool_name = input_data.get("tool_name", "")

    # Only check Bash commands
    if tool_name != "Bash":
        sys.exit(0)  # Allow non-Bash tools

    command = input_data.get("tool_input", {}).get("command", "")

    # Check if command calls system_health.py
    if "system_health.py" not in command:
        # Allow cd to __csf directory (common setup step)
        if "cd P:/__csf" in command or "cd P:\\\\__csf" in command:
            sys.exit(0)  # Allow directory change

        # Block incorrect commands with helpful message
        flags = (
            "--health, --quick, --all, --activity, --blocked, "
            "--tests, --evidence, --packages, --llm, --quota, "
            "--hooks, --json, --root <path>"
        )
        usage_msg = (
            "⛔ /main-hooks requires calling system_health.py.\n\n"
            "Use: cd P:/__csf && python src/modules/observability/system_health.py [flags]\n\n"
            f"Available flags: {flags}"
        )
        print(json.dumps({
            "hookSpecificOutput": {"additionalContext": usage_msg}
        }))
        sys.exit(2)  # Block

    sys.exit(0)  # Allow

if __name__ == "__main__":
    main()
