"""ProgressReporter - Real-time progress reporting for brainstorm phases.

Provides elapsed time tracking and status updates during brainstorm execution.
Outputs to stderr to avoid mixing with results.
"""

from __future__ import annotations

import sys
from datetime import datetime
from typing import TextIO


class ProgressReporter:
    """Reports progress during brainstorm phases with elapsed time tracking.

    Attributes:
        verbose: If True, output progress messages. If False, suppress all output.
        current_phase: Name of the current phase (e.g., "init", "diverge", "converge").
        personas_complete: Set of persona names that have completed.
        start_time: Timestamp when reset() was called, or None.
        output: Output stream for messages (default: sys.stderr).
    """

    def __init__(
        self,
        verbose: bool = True,
        output: TextIO | None = None,
    ) -> None:
        """Initialize ProgressReporter.

        Args:
            verbose: If True, output progress messages. Default True.
            output: Output stream for messages. Default sys.stderr.
        """
        self.verbose = verbose
        self.current_phase = "init"
        self.personas_complete: set[str] = set()
        self.start_time: datetime | None = None
        self.output: TextIO = output if output is not None else sys.stderr

    def reset(self) -> None:
        """Reset state for a new session.

        Clears current_phase to "init", clears personas_complete,
        and sets start_time to current time.
        """
        self.current_phase = "init"
        self.personas_complete.clear()
        self.start_time = datetime.now()

    def _get_elapsed_time_str(self) -> str:
        """Get formatted elapsed time string [MM:SS].

        Returns:
            Elapsed time in [MM:SS] format since reset() was called.
            Returns [00:00] if reset() hasn't been called yet.
        """
        if self.start_time is None:
            return "[00:00]"

        elapsed = datetime.now() - self.start_time
        total_seconds = int(elapsed.total_seconds())
        minutes = total_seconds // 60
        seconds = total_seconds % 60
        return f"[{minutes:02d}:{seconds:02d}]"

    def _emit(self, message: str) -> None:
        """Emit message to output stream if verbose mode is enabled.

        Args:
            message: The message to emit.
        """
        if self.verbose:
            self.output.write(message + "\n")

    def phase_start(self, phase: str, total_items: int = 0) -> None:
        """Report start of a new phase.

        Args:
            phase: Name of the phase (e.g., "diverge", "converge").
            total_items: Number of items to process in this phase. Default 0.
        """
        self.current_phase = phase
        elapsed = self._get_elapsed_time_str()

        if total_items > 0:
            self._emit(f"{elapsed} ▶ {phase.upper()} ({total_items} items)")
        else:
            self._emit(f"{elapsed} ▶ {phase.upper()}")

    def persona_complete(self, persona: str, idea_count: int) -> None:
        """Report completion of a persona's brainstorming.

        Args:
            persona: Name of the completed persona.
            idea_count: Number of ideas generated by this persona.
        """
        self.personas_complete.add(persona)
        elapsed = self._get_elapsed_time_str()
        self._emit(f"{elapsed} ✓ {persona}: {idea_count} ideas")

    def phase_complete(self, phase: str, result_count: int) -> None:
        """Report completion of a phase.

        Args:
            phase: Name of the completed phase.
            result_count: Number of results produced in this phase.
        """
        elapsed = self._get_elapsed_time_str()
        self._emit(f"{elapsed} ✓ {phase.upper()}: {result_count} results")
