import json
import tomllib
import os

# Paths
REGISTRY_PATH = r"P:/.claude/registry/commands.toml"
CLUSTERS_PATH = r"P:/.claude/registry/tech_tree_clusters.json"
OUTPUT_PATH = r"P:/.claude/docs/sdlc_data_injection.js"


def generate_data():
    try:
        # 1. Load Commands Registry (for Relationships)
        if os.path.exists(REGISTRY_PATH):
            with open(REGISTRY_PATH, "rb") as f:
                cmd_data = tomllib.load(f)
        else:
            print(f"Warning: {REGISTRY_PATH} not found. using empty commands data.")
            cmd_data = {}

        relationships = {}
        for key, cmd in cmd_data.get("commands", {}).items():
            # Standardize ID: use alias if available, else /key
            # But wait, looking at my previous work, I standardized on "/key" logic manually in the script?
            # Actually, `commands.toml` has keys like "design".
            # My previous script used cmd_id = "/"+key unless aliases existed.
            # I will stick to consistent logic: prefer explicit aliases if they start with /, else / + key.

            cmd_id = "/" + key
            if "aliases" in cmd and cmd["aliases"]:
                # Prefer the first alias that looks like a command (/...)
                for alias in cmd["aliases"]:
                    if alias.startswith("/"):
                        cmd_id = alias
                        break

            rel_data = {}
            if "suggests_next" in cmd:
                rel_data["next"] = [
                    ("/" + x if not x.startswith("/") and not x.startswith("@") else x)
                    for x in cmd["suggests_next"]
                ]
            if "triggers_after" in cmd:
                rel_data["prev"] = [
                    ("/" + x if not x.startswith("/") and not x.startswith("@") else x)
                    for x in cmd["triggers_after"]
                ]
            if "handles" in cmd:
                rel_data["capabilities"] = cmd["handles"]

            if rel_data:
                relationships[cmd_id] = rel_data

        # 2. Load Clusters Registry
        with open(CLUSTERS_PATH, encoding="utf-8") as f:
            clusters_data = json.load(f)

        # 3. Generate Output
        # We output a JS snippet that defines both constants

        js_output = f"""
        // AUTO-GENERATED BY generate_sdlc_tech_tree_data.py
        const RELATIONSHIPS = {json.dumps(relationships, indent=4)};

        const CLUSTERS = {json.dumps(clusters_data, indent=4)};
        """

        with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
            f.write(js_output)

        print(f"Generated data to {OUTPUT_PATH}")
        print(f"RELATIONSHIPS count: {len(relationships)}")
        print(f"CLUSTERS branches: {list(clusters_data.keys())}")

    except Exception as e:
        print(f"Error: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    generate_data()
