import json
import re
import sys
from datetime import date, datetime
from pathlib import Path

# Add hooks path to imports
hooks_path = Path("P:/.claude/hooks")
sys.path.insert(0, str(hooks_path))

try:
    from skill_registry import load_registry, SkillSpec
except ImportError:
    print("Could not import skill_registry. Make sure it exists in P:/.claude/hooks")
    sys.exit(1)

OUTPUT_FILE = r"P:/.claude/docs/sdlc_tech_tree/data/skills_metadata.js"


def enrich_skill_metadata(spec: SkillSpec) -> dict:
    """Enrich basic spec with deep content extraction (body parsing)."""

    # Base metadata from registry
    metadata = {
        "id": f"/{spec.name}",  # Standardize on slash-prefixed ID
        "name": spec.name,
        "description": spec.description,
        "category": spec.category,
        "filePath": spec.file_path,
        "directives": spec.directive,
        "doNot": spec.do_not,
        "defaultArgs": spec.default_args,
        "examples": spec.examples,
        "summary": spec.description,  # Alias for UI
        "howToUse": spec.directive  # Fallback/Alias
    }

    # Merge extra frontmatter fields
    if spec.metadata:
        metadata.update(spec.metadata)

    # Load content for deep body parsing (Modules, Pitfalls, etc.)
    try:
        content = Path(spec.file_path).read_text(encoding='utf-8')
        metadata["rawContent"] = content
    except Exception:
        content = ""
        metadata["rawContent"] = ""

    # 1. Extract Module Structure section if present
    module_match = re.search(
        r'## Module Structure.*?\n\n(.*?)(?:\n\n##|---)',
        content,
        re.DOTALL
    )
    if module_match:
        metadata['modules'] = module_match.group(1).strip()

    # 2. Extract Common Use Cases from Routing Decision table if exists
    use_cases = []
    use_case_table = re.search(
        r'### 4.2 Intent-Based Routing.*?\n\n(.*?)(?:\n\n##|---)',
        content,
        re.DOTALL
    )
    if use_case_table:
        table_content = use_case_table.group(1)
        lines = table_content.split('\n')
        for line in lines:
            if '|' in line and '/' in line:
                parts = [p.strip() for p in line.split('|')]
                if len(parts) >= 3:
                    use_cases.append(f"{parts[1]}: {parts[3]}")

    if use_cases:
        metadata['useCases'] = use_cases[:5]

    # 3. Extract Pitfalls
    pitfalls_match = re.search(
        r'\*\*Avoid:\*\*\s*\n\n(.*?)(?:\n\n|##)',
        content,
        re.DOTALL
    )
    if pitfalls_match:
        metadata['pitfalls'] = [
            p.strip('- ').strip()
            for p in pitfalls_match.group(1).split('\n')
            if p.strip()
        ]

    # 4. Handle 'suggest' normalization if present in metadata
    if 'suggest' in metadata:
        raw_suggest = metadata['suggest']
        if isinstance(raw_suggest, str):
            if raw_suggest.startswith('[') and raw_suggest.endswith(']'):
                metadata['suggest'] = [
                    s.strip(" '\"") for s in raw_suggest[1:-1].split(',')
                ]
            elif '\n' in raw_suggest:
                metadata['suggest'] = [
                    s.strip("- ") for s in raw_suggest.split('\n') if s.strip()
                ]

    # 5. Handle Date Serialization (PyYAML produces datetime objects)
    for key, value in metadata.items():
        if isinstance(value, (date, datetime)):
            metadata[key] = value.isoformat()

    return metadata


def main():
    print("Loading skill registry...")
    # Force reload to ensure fresh data
    registry = load_registry(force_reload=True)

    results = {}

    # Filter for unique unique specs (registry has aliases pointing to same spec)
    # Use name as unique key
    unique_specs = {}
    for key, spec in registry.items():
        unique_specs[spec.name] = spec

    print(f"Found {len(unique_specs)} unique skills in registry.")

    for name, spec in sorted(unique_specs.items()):
        try:
            meta = enrich_skill_metadata(spec)
            # Use slash-prefixed ID for consistency with old format
            results[f"/{name}"] = meta
            print(f"Processed: /{name}")
        except Exception as e:
            print(f"Error processing {name}: {e}")

    # Write output
    output_path = Path(OUTPUT_FILE)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by extract_skills.py using skill_registry\n")
        json_str = json.dumps(results, indent=4)
        f.write("window.SKILLS_METADATA = " + json_str + ";")

    print(f"Done! Saved {len(results)} skills to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
