[paths]
source = "D:\\_XPR\\Files\\3\\jav"
temp_dir = "C:\\TEMP\\ReencodedVideos"

[settings]
log_level = "INFO"
create_subtitles = true
no_replace = true
normalize_audio = true

[encoding]
target_height = 1080
crf = 0

[performance]
max_workers = 4

[quality]
vmaf_decision_enabled = true
vmaf_decision_threshold = 94.0
