#!/usr/bin/env python3
"""
Shared Evidence Manager for Universal Command Integration
Enables bidirectional context sharing and smart handoffs between commands
"""

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


@dataclass
class ProjectContext:
    """Universal project context shared across all commands"""
    project_id: str
    current_phase: str  # analysis, planning, execution, validation, completion
    completed_phases: list[str]
    active_commands: list[str]
    quality_scores: dict[str, float]
    evidence_summary: dict[str, Any]
    created_at: datetime
    last_updated: datetime

@dataclass
class CommandEvidence:
    """Evidence generated by a specific command"""
    command_name: str
    execution_time: datetime
    results_summary: str
    quality_metrics: dict[str, float]
    evidence_paths: list[str]
    handoff_ready: bool
    integration_points: list[str]
    can_continue_with: list[str]
    prerequisites_satisfied: bool

@dataclass
class IntegrationContext:
    """Context for command transitions and handoffs"""
    can_continue_with: list[str]
    next_recommended_steps: list[str]
    prerequisites_satisfied: bool
    transition_validity: dict[str, bool]
    shared_context: dict[str, Any]
    quality_gates_passed: list[str]

class SharedEvidenceManager:
    """Manages shared evidence and context across all commands"""

    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root)
        self.evidence_dir = self.project_root / ".speckit" / "evidence" / "shared"
        self.state_dir = self.project_root / ".speckit" / "state"
        self.cache_dir = self.project_root / ".speckit" / "cache"

        # Ensure directories exist
        self.evidence_dir.mkdir(parents=True, exist_ok=True)
        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    def generate_project_id(self, user_input: str) -> str:
        """Generate unique project ID based on user input and context"""
        timestamp = datetime.now().strftime("%Y%m%d-%H%M")
        content_hash = hashlib.md5(user_input.encode()).hexdigest()[:8]
        return f"TSK-{timestamp}-{content_hash.upper()}"

    def detect_existing_project(self) -> ProjectContext | None:
        """Detect existing project context"""
        # Look for recent project state files
        state_files = list(self.state_dir.glob("project_*.json"))
        if not state_files:
            return None

        # Get most recent state file
        latest_file = max(state_files, key=lambda f: f.stat().st_mtime)

        try:
            with open(latest_file) as f:
                data = json.load(f)
                return ProjectContext(
                    project_id=data['project_id'],
                    current_phase=data['current_phase'],
                    completed_phases=data['completed_phases'],
                    active_commands=data['active_commands'],
                    quality_scores=data['quality_scores'],
                    evidence_summary=data['evidence_summary'],
                    created_at=datetime.fromisoformat(data['created_at']),
                    last_updated=datetime.fromisoformat(data['last_updated'])
                )
        except (KeyError, json.JSONDecodeError, ValueError):
            return None

    def create_project_context(self, user_input: str, initial_command: str) -> ProjectContext:
        """Create new project context"""
        project_id = self.generate_project_id(user_input)

        context = ProjectContext(
            project_id=project_id,
            current_phase="analysis",
            completed_phases=[],
            active_commands=[initial_command],
            quality_scores={},
            evidence_summary={},
            created_at=datetime.now(),
            last_updated=datetime.now()
        )

        self.save_project_context(context)
        return context

    def save_project_context(self, context: ProjectContext):
        """Save project context to file"""
        context.last_updated = datetime.now()

        state_file = self.state_dir / f"project_{context.project_id}.json"

        with open(state_file, 'w') as f:
            json.dump({
                'project_id': context.project_id,
                'current_phase': context.current_phase,
                'completed_phases': context.completed_phases,
                'active_commands': context.active_commands,
                'quality_scores': context.quality_scores,
                'evidence_summary': context.evidence_summary,
                'created_at': context.created_at.isoformat(),
                'last_updated': context.last_updated.isoformat()
            }, f, indent=2)

    def detect_previous_work(self, current_command: str) -> dict[str, Any]:
        """Detect what work has been done by other commands"""
        context = self.detect_existing_project()
        if not context:
            return {}

        detected_work = {
            'project_context': context,
            'ask_completed': self.check_command_evidence('/ask'),
            'research_completed': self.check_command_evidence('/research'),
            'planning_done': self.check_command_evidence('/speckit.plan'),
            'cwo12_active': self.check_command_evidence('/cwo12'),
            'execution_started': self.check_command_evidence('/exec'),
            'validation_done': self.check_command_evidence('/gw.code-review'),
            'qual_gates_passed': self.check_command_evidence('/qual-gate'),
            'explore_done': self.check_command_evidence('/explore'),
            'learn_done': self.check_command_evidence('/learn'),
            'task_active': self.check_command_evidence('/task'),
            'git_active': self.check_command_evidence('/git'),
            'sap_done': self.check_command_evidence('/sap'),
            'specify_done': self.check_command_evidence('/specify')
        }

        return detected_work

    def check_command_evidence(self, command_name: str) -> CommandEvidence | None:
        """Check for evidence from a specific command"""
        evidence_files = list(self.evidence_dir.glob(f"{command_name.replace('/', '_')}*.json"))
        if not evidence_files:
            return None

        # Get most recent evidence file
        latest_file = max(evidence_files, key=lambda f: f.stat().st_mtime)

        try:
            with open(latest_file) as f:
                data = json.load(f)
                return CommandEvidence(
                    command_name=data['command_name'],
                    execution_time=datetime.fromisoformat(data['execution_time']),
                    results_summary=data['results_summary'],
                    quality_metrics=data['quality_metrics'],
                    evidence_paths=data['evidence_paths'],
                    handoff_ready=data['handoff_ready'],
                    integration_points=data['integration_points'],
                    can_continue_with=data['can_continue_with'],
                    prerequisites_satisfied=data['prerequisites_satisfied']
                )
        except (KeyError, json.JSONDecodeError, ValueError):
            return None

    def save_command_evidence(self, evidence: CommandEvidence):
        """Save evidence from a command execution"""
        timestamp = evidence.execution_time.strftime("%Y%m%d_%H%M%S")
        filename = f"{evidence.command_name.replace('/', '_')}_{timestamp}.json"
        evidence_file = self.evidence_dir / filename

        with open(evidence_file, 'w') as f:
            json.dump({
                'command_name': evidence.command_name,
                'execution_time': evidence.execution_time.isoformat(),
                'results_summary': evidence.results_summary,
                'quality_metrics': evidence.quality_metrics,
                'evidence_paths': evidence.evidence_paths,
                'handoff_ready': evidence.handoff_ready,
                'integration_points': evidence.integration_points,
                'can_continue_with': evidence.can_continue_with,
                'prerequisites_satisfied': evidence.prerequisites_satisfied
            }, f, indent=2)

    def create_integration_context(self, from_command: str, to_command: str,
                                 detected_work: dict[str, Any]) -> IntegrationContext:
        """Create integration context for command handoff"""

        # Load capability mappings
        capabilities = self._load_command_capabilities()

        # Determine compatibility
        from_cap = capabilities.get(from_command, {})
        to_cap = capabilities.get(to_command, {})

        can_handoff = to_command in from_cap.get('can_handoff_to', [])
        can_inherit = from_command in to_cap.get('can_inherit_from', [])

        # Analyze completed phases and quality gates
        completed_phases = []
        if detected_work.get('ask_completed'):
            completed_phases.append('input_analysis')
        if detected_work.get('research_completed'):
            completed_phases.append('requirements_research')
        if detected_work.get('planning_done'):
            completed_phases.append('strategic_planning')
        if detected_work.get('execution_started'):
            completed_phases.append('implementation')
        if detected_work.get('validation_done'):
            completed_phases.append('quality_validation')

        # Determine next recommended steps
        next_steps = self._determine_next_steps(to_command, completed_phases, detected_work)

        return IntegrationContext(
            can_continue_with=to_cap.get('can_continue_with', []),
            next_recommended_steps=next_steps,
            prerequisites_satisfied=can_inherit and can_handoff,
            transition_validity={
                'handoff_possible': can_handoff,
                'inheritance_possible': can_inherit,
                'context_preserved': bool(detected_work.get('project_context'))
            },
            shared_context=detected_work,
            quality_gates_passed=self._check_quality_gates(detected_work)
        )

    def _load_command_capabilities(self) -> dict[str, dict[str, Any]]:
        """Load command capability mappings"""
        # This would typically load from the integration YAML file
        return {
            "/ask": {
                "can_inherit_from": ["/research", "/learn", "/truth", "/explore", "/nse"],
                "can_handoff_to": ["/cwo12", "/speckit.plan", "/exec", "/research"],
                "primary_strength": "truth-validated analysis"
            },
            "/cwo12": {
                "can_inherit_from": ["any_command"],
                "can_handoff_to": ["any_command"],
                "primary_strength": "complete workflow orchestration"
            },
            "/research": {
                "can_inherit_from": ["/ask", "/learn", "/explore", "/truth"],
                "can_handoff_to": ["/cwo12", "/speckit.plan", "/ask", "/exec"],
                "primary_strength": "comprehensive evidence gathering"
            },
            "/exec": {
                "can_inherit_from": ["/cwo12", "/speckit.plan", "/ask", "/task"],
                "can_handoff_to": ["/cwo12", "/gw.code-review", "/test-fix"],
                "primary_strength": "enhanced implementation execution"
            },
            "/speckit.plan": {
                "can_inherit_from": ["/ask", "/research", "/arch", "/specify"],
                "can_handoff_to": ["/cwo12", "/exec", "/ask"],
                "primary_strength": "architect-led strategic planning"
            },
            "/gw.code-review": {
                "can_inherit_from": ["/exec", "/cwo12", "/ask", "/test-fix"],
                "can_handoff_to": ["/cwo12", "/exec", "/security-validator"],
                "primary_strength": "multi-tool specialist validation"
            },
            "/qual-gate": {
                "can_inherit_from": ["any_command"],
                "can_handoff_to": ["any_command"],
                "primary_strength": "intelligent quality orchestration"
            }
        }

    def _determine_next_steps(self, target_command: str, completed_phases: list[str],
                            detected_work: dict[str, Any]) -> list[str]:
        """Determine recommended next steps based on current state"""
        next_steps = []

        if target_command == "/cwo12":
            if not completed_phases:
                next_steps.append("Start with Step 1: Input Analysis & Quality Assessment")
            elif "input_analysis" in completed_phases and "requirements_research" not in completed_phases:
                next_steps.append("Continue with Step 2: GW.ASK Enhanced Analysis")
            elif "strategic_planning" not in completed_phases:
                next_steps.append("Continue with Step 3: Strategic Planning & Resource Allocation")
            else:
                next_steps.append("Continue from appropriate step based on completed work")

        elif target_command == "/exec":
            if "strategic_planning" not in completed_phases:
                next_steps.append("Complete planning phase first")
            next_steps.append("Proceed with enhanced execution (60% improvement)")

        elif target_command == "/research":
            next_steps.append("Conduct comprehensive research with evidence gathering")
            if detected_work.get('ask_completed'):
                next_steps.append("Build upon existing /ask analysis")

        return next_steps

    def _check_quality_gates(self, detected_work: dict[str, Any]) -> list[str]:
        """Check which quality gates have been passed"""
        passed_gates = []

        if detected_work.get('qual_gates_passed'):
            passed_gates.extend(["foundation", "constitution", "architecture"])

        if detected_work.get('ask_completed') and detected_work['ask_completed'].quality_metrics.get('overall_quality', 0) >= 0.85:
            passed_gates.append("input_validation")

        if detected_work.get('research_completed') and detected_work['research_completed'].quality_metrics.get('evidence_quality', 0) >= 0.90:
            passed_gates.append("research_validation")

        return passed_gates

# Global instance for easy access
evidence_manager = SharedEvidenceManager()
