#!/usr/bin/env python3
"""
RCA Metrics Tracker

Tracks debugging and Root Cause Analysis metrics for continuous improvement.
Replaces "TBD" placeholders in debug_unified_inst.md with actual measurements.

Metrics tracked:
- CHS usage rate
- Quick-fix success rate
- Fix verification rate
- Recurrence rate (7-day, 30-day)
- Average time to resolution
- CHS hit rate

Author: CSF Development Team
Version: 1.0.2
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path

# Computed project root (Python 3.12+)
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent
class MatchType(Enum):
    """Types of CHS matches"""

    EXACT = "exact"  # Same error, same file, known fix
    PATTERN = "pattern"  # Similar error pattern
    NONE = "none"  # No relevant results


class FixType(Enum):
    """Types of fixes applied"""

    QUICK_FIX = "quick_fix"  # Applied directly from CHS
    RCA_SPECIALIST = "rca_specialist"  # Generated by rca-specialist
    MANUAL = "manual"  # Manual intervention


class ProblemType(Enum):
    """Types of problems"""

    ERROR = "error"  # Exception/error thrown
    CRASH = "crash"  # Process terminated
    PERFORMANCE = "performance"  # Slowness/resource issue
    BEHAVIOR = "behavior"  # Unexpected behavior
    BUILD = "build"  # Compilation/build failure
    TEST = "test"  # Test failure
    UNKNOWN = "unknown"  # Cannot classify


@dataclass
class RCAMetrics:
    """Aggregate RCA metrics"""

    chs_usage_rate: float = 0.0  # % of /debug invocations with CHS execution
    quick_fix_success_rate: float = 0.0  # % of exact matches that worked
    fix_verification_rate: float = 0.0  # % of fixes verified with tests
    recurrence_rate_7d: float = 0.0  # % of problems recurring within 7 days
    recurrence_rate_30d: float = 0.0  # % of problems recurring within 30 days
    avg_time_exact_match: float = 0.0  # Avg minutes for exact match resolution
    avg_time_new_issue: float = 0.0  # Avg minutes for new issue resolution
    chs_hit_rate: float = 0.0  # % of CHS queries with useful results
    total_rcas: int = 0  # Total RCA sessions tracked
    delegation_compliance_rate: float = 0.0  # % of expected delegations that executed
    delegation_expected: int = 0  # Total expected delegation events
    delegation_executed: int = 0  # Total executed delegation events
    # Claim verification metrics (Layer 1-3 enforcement)
    claim_accuracy_rate: float = 0.0  # % of claims verified as correct
    claims_verified: int = 0  # Total claims checked
    claims_correct: int = 0  # Claims verified as correct
    claims_false: int = 0  # Claims detected as false


@dataclass
class RCASession:
    """A single RCA/debug session"""

    session_id: str
    problem_hash: str
    problem_type: str
    started_at: str
    completed_at: str | None = None
    chs_results_count: int = 0
    chs_match_type: str = MatchType.NONE.value
    cks_results_count: int = 0
    fix_type: str | None = None
    fix_applied: bool = False
    verification_passed: bool | None = None
    time_to_resolution_minutes: float | None = None


# SEC-002: Maximum input length for problem_hash to prevent DoS
MAX_INPUT_LENGTH = 10_000


def problem_hash(problem_description: str, context: str | dict = "") -> str:
    """Generate consistent hash for a problem.

    SEC-002: Validates input length to prevent potential DoS attacks via
    excessively long problem descriptions or context data.

    Args:
        problem_description: Description of the problem (max 10_000 chars)
        context: Additional context (string or dict, max 10_000 chars when serialized)

    Returns:
        16-character hex hash of the problem and context

    Raises:
        ValueError: If problem_description or serialized context exceeds MAX_INPUT_LENGTH
    """
    # SEC-002: Validate problem_description length
    if problem_description is None:
        problem_description = ""
    if len(problem_description) > MAX_INPUT_LENGTH:
        raise ValueError(
            f"Input exceeds maximum length: {len(problem_description)} > {MAX_INPUT_LENGTH}"
        )

    # Normalize context to string
    if isinstance(context, dict):
        context_str = json.dumps(context, sort_keys=True)
    elif context is None:
        context_str = ""
    else:
        context_str = str(context)

    # SEC-002: Validate context length
    if len(context_str) > MAX_INPUT_LENGTH:
        raise ValueError(
            f"Context exceeds maximum length: {len(context_str)} > {MAX_INPUT_LENGTH}"
        )

    # Convert to lowercase and strip for consistent hashing
    content = f"{problem_description.lower().strip()}|{context_str.lower().strip()}"
    return hashlib.sha256(content.encode()).hexdigest()[:16]


class RCAMetricsTracker:
    """
    Tracks RCA/debug metrics for continuous improvement.

    Thread-safe, async-friendly metrics recording with SQLite persistence.
    """

    def __init__(self, db_path: Path | None = None):
        """
        Initialize metrics tracker.

        Args:
            db_path: Path to metrics database. Defaults to TaskMaster DB.

        """
        if db_path is None:
            db_path = PROJECT_ROOT / ".speckit" / "taskmaster" / "tasks.db"

        self.db_path = db_path
        self._lock = threading.Lock()
        self._init_db()

    def _init_db(self) -> None:
        """Initialize metrics database schema."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS rca_sessions (
                    session_id TEXT PRIMARY KEY,
                    problem_hash TEXT NOT NULL,
                    problem_type TEXT NOT NULL,
                    started_at TEXT NOT NULL,
                    completed_at TEXT,
                    chs_results_count INTEGER DEFAULT 0,
                    chs_match_type TEXT DEFAULT 'none',
                    cks_results_count INTEGER DEFAULT 0,
                    fix_type TEXT,
                    fix_applied INTEGER DEFAULT 0,
                    verification_passed INTEGER,
                    time_to_resolution_minutes REAL
                )
            """)

            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_rca_sessions_problem_hash
                ON rca_sessions(problem_hash)
            """)

            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_rca_sessions_started_at
                ON rca_sessions(started_at)
            """)

            conn.execute("""
                CREATE TABLE IF NOT EXISTS rca_delegation_events (
                    session_id TEXT PRIMARY KEY,
                    expected_count INTEGER NOT NULL DEFAULT 0,
                    executed_count INTEGER NOT NULL DEFAULT 0,
                    source TEXT DEFAULT 'rca',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )
            """)

            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_rca_delegation_created_at
                ON rca_delegation_events(created_at)
            """)

            conn.commit()

    def record_rca_start(
        self,
        problem_description: str,
        problem_type: ProblemType = ProblemType.UNKNOWN,
        context: str = "",
    ) -> str:
        """
        Record the start of an RCA session.

        Args:
            problem_description: The problem being debugged
            problem_type: Type of problem
            context: Additional context (file, component, etc.)

        Returns:
            Session ID for this RCA session

        """
        session_id = f"rca_{int(time.time() * 1000)}"
        phash = problem_hash(problem_description, context)
        started_at = datetime.now().isoformat()

        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                INSERT INTO rca_sessions (
                    session_id, problem_hash, problem_type, started_at
                ) VALUES (?, ?, ?, ?)
            """,
                (session_id, phash, problem_type.value, started_at),
            )
            conn.commit()

        return session_id

    def record_chs_results(
        self, session_id: str, results_count: int, match_type: MatchType
    ) -> None:
        """
        Record CHS search results for a session.

        Args:
            session_id: The RCA session ID
            results_count: Number of CHS results found
            match_type: Type of match (exact, pattern, none)

        """
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                UPDATE rca_sessions
                SET chs_results_count = ?, chs_match_type = ?
                WHERE session_id = ?
            """,
                (results_count, match_type.value, session_id),
            )
            conn.commit()

    def record_cks_results(self, session_id: str, results_count: int) -> None:
        """
        Record CKS search results for a session.

        Args:
            session_id: The RCA session ID
            results_count: Number of CKS results found

        """
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                UPDATE rca_sessions
                SET cks_results_count = ?
                WHERE session_id = ?
            """,
                (results_count, session_id),
            )
            conn.commit()

    def record_fix_attempt(
        self, session_id: str, fix_type: FixType, fix_description: str | None = None
    ) -> None:
        """
        Record a fix attempt for a session.

        Args:
            session_id: The RCA session ID
            fix_type: Type of fix applied
            fix_description: Description of the fix (for future reference)

        """
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                UPDATE rca_sessions
                SET fix_type = ?, fix_applied = 1
                WHERE session_id = ?
            """,
                (fix_type.value, session_id),
            )
            conn.commit()

    def record_verification(
        self, session_id: str, passed: bool, verification_command: str | None = None
    ) -> None:
        """
        Record fix verification result.

        Args:
            session_id: The RCA session ID
            passed: Whether verification passed
            verification_command: Command used for verification

        """
        completed_at = datetime.now().isoformat()

        # Calculate time to resolution
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                "SELECT started_at FROM rca_sessions WHERE session_id = ?",
                (session_id,),
            )
            row = cursor.fetchone()
            if row:
                started = datetime.fromisoformat(row[0])
                completed = datetime.fromisoformat(completed_at)
                time_minutes = (completed - started).total_seconds() / 60

                conn.execute(
                    """
                    UPDATE rca_sessions
                    SET completed_at = ?, verification_passed = ?, time_to_resolution_minutes = ?
                    WHERE session_id = ?
                """,
                    (completed_at, int(passed), time_minutes, session_id),
                )
                conn.commit()

    def record_delegation_event(
        self,
        session_id: str,
        expected_count: int = 1,
        executed_count: int = 0,
        source: str = "rca",
    ) -> None:
        """
        Record or update delegation KPI event for a session.

        Uses upsert semantics to preserve max observed expected/executed counts
        when the same session is updated multiple times by hooks.
        """
        now = datetime.now().isoformat()
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                INSERT INTO rca_delegation_events (
                    session_id, expected_count, executed_count, source, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?)
                ON CONFLICT(session_id) DO UPDATE SET
                    expected_count = MAX(rca_delegation_events.expected_count, excluded.expected_count),
                    executed_count = MAX(rca_delegation_events.executed_count, excluded.executed_count),
                    source = excluded.source,
                    updated_at = excluded.updated_at
                """,
                (
                    session_id,
                    max(0, int(expected_count)),
                    max(0, int(executed_count)),
                    source,
                    now,
                    now,
                ),
            )
            conn.commit()

    def record_claim_verdict(
        self,
        session_id: str,
        claim_type: str,
        verdict: str,
        confidence: float = 0.0,
        metadata: dict | None = None,
    ) -> None:
        """
        Record a claim verification verdict for tracking claim accuracy.

        Args:
            session_id: The RCA/debug session ID
            claim_type: Type of claim (output_claim, file_claim, etc.)
            verdict: Verdict (CORRECT, FALSE, PARTIAL, UNVERIFIED)
            confidence: Confidence score of the detection (0.0-1.0)
            metadata: Additional metadata (claim text, etc.)

        This tracks the effectiveness of the ClaimGuard hook in preventing
        false claims about tool outputs.
        """
        now = datetime.now().isoformat()
        with sqlite3.connect(self.db_path) as conn:
            # Create table if not exists
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS rca_claim_verifications (
                    id TEXT PRIMARY KEY,
                    session_id TEXT NOT NULL,
                    claim_type TEXT NOT NULL,
                    verdict TEXT NOT NULL,
                    confidence REAL DEFAULT 0.0,
                    metadata TEXT,
                    created_at TEXT NOT NULL
                )
            """
            )

            # Generate unique ID with timestamp + thread_id + counter to prevent collisions
            thread_id = threading.get_ident() % 10000  # Last 4 digits of thread ID
            timestamp_ms = int(time.time() * 1000)
            claim_id = f"claim_{timestamp_ms}_{thread_id}"
            metadata_json = json.dumps(metadata) if metadata else None

            conn.execute(
                """
                INSERT INTO rca_claim_verifications
                (id, session_id, claim_type, verdict, confidence, metadata, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
                (claim_id, session_id, claim_type, verdict, confidence, metadata_json, now),
            )
            conn.commit()

    def get_delegation_metrics(self, days: int = 30) -> dict:
        """Get delegation KPI aggregates for a reporting window."""
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()
        with sqlite3.connect(self.db_path) as conn:
            try:
                cursor = conn.execute(
                    """
                    SELECT
                        COALESCE(SUM(expected_count), 0) AS expected_total,
                        COALESCE(SUM(executed_count), 0) AS executed_total,
                        COUNT(*) AS sessions
                    FROM rca_delegation_events
                    WHERE created_at > ?
                    """,
                    (cutoff,),
                )
                row = cursor.fetchone() or (0, 0, 0)
                expected_total, executed_total, sessions = int(row[0] or 0), int(row[1] or 0), int(row[2] or 0)
            except sqlite3.OperationalError:
                expected_total, executed_total, sessions = 0, 0, 0

        rate = (executed_total / expected_total * 100) if expected_total > 0 else 0.0
        return {
            "expected": expected_total,
            "executed": executed_total,
            "missing": max(expected_total - executed_total, 0),
            "sessions": sessions,
            "compliance_rate": round(rate, 1),
        }

    def record_recurrence(
        self, original_problem_hash: str, new_session_id: str
    ) -> None:
        """
        Record that a problem has recurred.

        Args:
            original_problem_hash: Hash of the original problem
            new_session_id: Session ID of the recurrence

        """
        # Store recurrence in a separate table for analysis
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS rca_recurrences (
                    id TEXT PRIMARY KEY,
                    original_problem_hash TEXT NOT NULL,
                    original_session_id TEXT,
                    new_session_id TEXT NOT NULL,
                    recurred_at TEXT NOT NULL,
                    days_since_original REAL,
                    INDEX (original_problem_hash),
                    INDEX (recurred_at)
                )
            """)

            # Get original session info
            cursor = conn.execute(
                """
                SELECT session_id, started_at
                FROM rca_sessions
                WHERE problem_hash = ?
                ORDER BY started_at ASC
                LIMIT 1
            """,
                (original_problem_hash,),
            )

            original = cursor.fetchone()
            if original:
                original_session_id, original_started = original
                original_time = datetime.fromisoformat(original_started)
                recurrence_time = datetime.now()
                days_since = (recurrence_time - original_time).days

                recurrence_id = f"rec_{int(time.time() * 1000)}"
                conn.execute(
                    """
                    INSERT INTO rca_recurrences (
                        id, original_problem_hash, original_session_id,
                        new_session_id, recurred_at, days_since_original
                    ) VALUES (?, ?, ?, ?, ?, ?)
                """,
                    (
                        recurrence_id,
                        original_problem_hash,
                        original_session_id,
                        new_session_id,
                        recurrence_time.isoformat(),
                        days_since,
                    ),
                )
                conn.commit()

    def get_metrics(self, days: int = 30) -> RCAMetrics:
        """
        Calculate aggregate metrics for a time period.

        Args:
            days: Number of days to look back (default: 30)

        Returns:
            RCAMetrics with calculated values

        """
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()

        with sqlite3.connect(self.db_path) as conn:
            # Total sessions in period
            cursor = conn.execute(
                """
                SELECT COUNT(*) FROM rca_sessions
                WHERE started_at > ?
            """,
                (cutoff,),
            )
            total_sessions = cursor.fetchone()[0] or 0

            # CHS usage rate (sessions with CHS query)
            cursor = conn.execute(
                """
                SELECT COUNT(DISTINCT session_id) FROM rca_sessions
                WHERE started_at > ? AND chs_results_count >= 0
            """,
                (cutoff,),
            )
            chs_used = cursor.fetchone()[0] or 0
            chs_usage_rate = (
                (chs_used / total_sessions * 100) if total_sessions > 0 else 0
            )

            # Quick-fix success rate (exact matches that passed verification)
            cursor = conn.execute(
                """
                SELECT COUNT(*) FROM rca_sessions
                WHERE started_at > ?
                AND chs_match_type = 'exact'
                AND verification_passed = 1
            """,
                (cutoff,),
            )
            successful_quick_fixes = cursor.fetchone()[0] or 0

            cursor = conn.execute(
                """
                SELECT COUNT(*) FROM rca_sessions
                WHERE started_at > ?
                AND chs_match_type = 'exact'
            """,
                (cutoff,),
            )
            total_quick_fixes = cursor.fetchone()[0] or 0
            quick_fix_success_rate = (
                (successful_quick_fixes / total_quick_fixes * 100)
                if total_quick_fixes > 0
                else 0
            )

            # Fix verification rate
            cursor = conn.execute(
                """
                SELECT COUNT(*) FROM rca_sessions
                WHERE started_at > ?
                AND fix_applied = 1
                AND verification_passed IS NOT NULL
            """,
                (cutoff,),
            )
            verified_fixes = cursor.fetchone()[0] or 0

            cursor = conn.execute(
                """
                SELECT COUNT(*) FROM rca_sessions
                WHERE started_at > ?
                AND fix_applied = 1
            """,
                (cutoff,),
            )
            total_fixes = cursor.fetchone()[0] or 0
            fix_verification_rate = (
                (verified_fixes / total_fixes * 100) if total_fixes > 0 else 0
            )

            # Recurrence rate (7-day)
            seven_days_ago = (datetime.now() - timedelta(days=7)).isoformat()
            try:
                cursor = conn.execute(
                    """
                    SELECT COUNT(DISTINCT original_problem_hash)
                    FROM rca_recurrences
                    WHERE recurred_at > ? AND days_since_original <= 7
                """,
                    (seven_days_ago,),
                )
                recurrences_7d = cursor.fetchone()[0] or 0
            except sqlite3.OperationalError:
                recurrences_7d = 0  # Table doesn't exist yet

            cursor = conn.execute(
                """
                SELECT COUNT(DISTINCT problem_hash)
                FROM rca_sessions
                WHERE started_at > ? AND fix_applied = 1 AND verification_passed = 1
            """,
                (seven_days_ago,),
            )
            total_resolved_7d = cursor.fetchone()[0] or 0
            recurrence_rate_7d = (
                (recurrences_7d / total_resolved_7d * 100)
                if total_resolved_7d > 0
                else 0
            )

            # Recurrence rate (30-day)
            try:
                cursor = conn.execute(
                    """
                    SELECT COUNT(DISTINCT original_problem_hash)
                    FROM rca_recurrences
                    WHERE recurred_at > ? AND days_since_original <= 30
                """,
                    (cutoff,),
                )
                recurrences_30d = cursor.fetchone()[0] or 0
            except sqlite3.OperationalError:
                recurrences_30d = 0  # Table doesn't exist yet

            cursor = conn.execute(
                """
                SELECT COUNT(DISTINCT problem_hash)
                FROM rca_sessions
                WHERE started_at > ? AND fix_applied = 1 AND verification_passed = 1
            """,
                (cutoff,),
            )
            total_resolved_30d = cursor.fetchone()[0] or 0
            recurrence_rate_30d = (
                (recurrences_30d / total_resolved_30d * 100)
                if total_resolved_30d > 0
                else 0
            )

            # Average time to resolution (exact match)
            cursor = conn.execute(
                """
                SELECT AVG(time_to_resolution_minutes)
                FROM rca_sessions
                WHERE started_at > ?
                AND chs_match_type = 'exact'
                AND time_to_resolution_minutes IS NOT NULL
            """,
                (cutoff,),
            )
            avg_time_exact = cursor.fetchone()[0] or 0.0

            # Average time to resolution (new issue)
            cursor = conn.execute(
                """
                SELECT AVG(time_to_resolution_minutes)
                FROM rca_sessions
                WHERE started_at > ?
                AND chs_match_type != 'exact'
                AND time_to_resolution_minutes IS NOT NULL
            """,
                (cutoff,),
            )
            avg_time_new = cursor.fetchone()[0] or 0.0

            # CHS hit rate (sessions with useful results)
            cursor = conn.execute(
                """
                SELECT COUNT(*) FROM rca_sessions
                WHERE started_at > ?
                AND (chs_match_type = 'exact' OR chs_match_type = 'pattern')
            """,
                (cutoff,),
            )
            chs_hits = cursor.fetchone()[0] or 0
            chs_hit_rate = (
                (chs_hits / total_sessions * 100) if total_sessions > 0 else 0
            )

            # Delegation compliance (expected vs executed)
            try:
                cursor = conn.execute(
                    """
                    SELECT
                        COALESCE(SUM(expected_count), 0),
                        COALESCE(SUM(executed_count), 0)
                    FROM rca_delegation_events
                    WHERE created_at > ?
                    """,
                    (cutoff,),
                )
                row = cursor.fetchone() or (0, 0)
                delegation_expected = int(row[0] or 0)
                delegation_executed = int(row[1] or 0)
            except sqlite3.OperationalError:
                delegation_expected = 0
                delegation_executed = 0
            delegation_compliance_rate = (
                (delegation_executed / delegation_expected * 100)
                if delegation_expected > 0
                else 0.0
            )

            # Claim verification metrics (Layer 1-3 enforcement)
            try:
                cursor = conn.execute(
                    """
                    SELECT
                        COUNT(*) as total,
                        SUM(CASE WHEN verdict = 'CORRECT' THEN 1 ELSE 0 END) as correct,
                        SUM(CASE WHEN verdict = 'FALSE' THEN 1 ELSE 0 END) as false_claims
                    FROM rca_claim_verifications
                    WHERE created_at > ?
                    """,
                    (cutoff,),
                )
                row = cursor.fetchone() or (0, 0, 0)
                claims_verified = int(row[0] or 0)
                claims_correct = int(row[1] or 0)
                claims_false = int(row[2] or 0)
            except sqlite3.OperationalError:
                claims_verified = 0
                claims_correct = 0
                claims_false = 0

            claim_accuracy_rate = (
                (claims_correct / claims_verified * 100) if claims_verified > 0 else 0.0
            )

        return RCAMetrics(
            chs_usage_rate=round(chs_usage_rate, 1),
            quick_fix_success_rate=round(quick_fix_success_rate, 1),
            fix_verification_rate=round(fix_verification_rate, 1),
            recurrence_rate_7d=round(recurrence_rate_7d, 1),
            recurrence_rate_30d=round(recurrence_rate_30d, 1),
            avg_time_exact_match=round(avg_time_exact, 1),
            avg_time_new_issue=round(avg_time_new, 1),
            chs_hit_rate=round(chs_hit_rate, 1),
            total_rcas=total_sessions,
            delegation_compliance_rate=round(delegation_compliance_rate, 1),
            delegation_expected=delegation_expected,
            delegation_executed=delegation_executed,
            claim_accuracy_rate=round(claim_accuracy_rate, 1),
            claims_verified=claims_verified,
            claims_correct=claims_correct,
            claims_false=claims_false,
        )

    def get_metrics_report(self, days: int = 30) -> str:
        """
        Generate a formatted metrics report.

        Args:
            days: Number of days to report on

        Returns:
            Formatted metrics report string

        """
        metrics = self.get_metrics(days)

        # Compare against targets

        def status_icon(
            value: float, target: float, lower_is_better: bool = False
        ) -> str:
            if lower_is_better:
                return "✅" if value <= target else "⚠️"
            return "✅" if value >= target else "⚠️"

        report = f"""
## RCA Metrics Report ({days}-day period)

**Total RCA Sessions:** {metrics.total_rcas}

### Success Metrics vs Targets

| Metric | Current | Target | Status |
|--------|---------|--------|--------|
| CHS Usage Rate | {metrics.chs_usage_rate}% | 100% | {status_icon(metrics.chs_usage_rate, 100)} |
| Quick-Fix Success Rate | {metrics.quick_fix_success_rate}% | 80% | {status_icon(metrics.quick_fix_success_rate, 80)} |
| Fix Verification Rate | {metrics.fix_verification_rate}% | 100% | {status_icon(metrics.fix_verification_rate, 100)} |
| Recurrence Rate (7d) | {metrics.recurrence_rate_7d}% | <10% | {status_icon(metrics.recurrence_rate_7d, 10, True)} |
| Recurrence Rate (30d) | {metrics.recurrence_rate_30d}% | <20% | {status_icon(metrics.recurrence_rate_30d, 20, True)} |
| Avg Time (Exact Match) | {metrics.avg_time_exact_match} min | <2 min | {status_icon(metrics.avg_time_exact_match, 2, True)} |
| Avg Time (New Issue) | {metrics.avg_time_new_issue} min | <15 min | {status_icon(metrics.avg_time_new_issue, 15, True)} |
| CHS Hit Rate | {metrics.chs_hit_rate}% | >60% | {status_icon(metrics.chs_hit_rate, 60)} |
| Delegation Compliance | {metrics.delegation_compliance_rate}% | 100% | {status_icon(metrics.delegation_compliance_rate, 100)} |

### Delegation KPIs

- Expected delegations: {metrics.delegation_expected}
- Executed delegations: {metrics.delegation_executed}
- Missing delegations: {max(metrics.delegation_expected - metrics.delegation_executed, 0)}

### Trend Analysis

"""
        # Add trend analysis if we have enough data
        if days >= 7:
            metrics_7d = self.get_metrics(7)
            report += f"**7-day vs {days}-day comparison:**\n\n"
            report += f"- Quick-fix success: {metrics_7d.quick_fix_success_rate}% → {metrics.quick_fix_success_rate}%\n"
            report += f"- Recurrence rate: {metrics_7d.recurrence_rate_7d}% → {metrics.recurrence_rate_7d}%\n"
            report += f"- Avg resolution time: {metrics_7d.avg_time_new_issue} min → {metrics.avg_time_new_issue} min\n"

        return report

    def get_top_recurring_problems(self, days: int = 30, limit: int = 10) -> list[dict]:
        """
        Get the most frequently recurring problems.

        Args:
            days: Days to look back
            limit: Maximum results to return

        Returns:
            List of recurring problem summaries

        """
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()

        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                """
                SELECT
                    r.problem_hash,
                    r.problem_type,
                    COUNT(r.recurred_at) as recurrence_count,
                    MAX(s.started_at) as first_seen,
                    MAX(r.recurred_at) as last_recurrence
                FROM rca_recurrences r
                JOIN rca_sessions s ON r.original_problem_hash = s.problem_hash
                WHERE r.recurred_at > ?
                GROUP BY r.problem_hash
                ORDER BY recurrence_count DESC
                LIMIT ?
            """,
                (cutoff, limit),
            )

            results = []
            for row in cursor.fetchall():
                results.append(
                    {
                        "problem_hash": row[0],
                        "problem_type": row[1],
                        "recurrence_count": row[2],
                        "first_seen": row[3],
                        "last_recurrence": row[4],
                    }
                )

            return results

    def check_for_recurrence(
        self, problem_description: str, context: str = "", days_lookback: int = 30
    ) -> str | None:
        """
        Check if this problem has been seen before.

        Args:
            problem_description: Current problem description
            context: Additional context
            days_lookback: How many days to look back

        Returns:
            Original session ID if recurrence found, None otherwise

        """
        phash = problem_hash(problem_description, context)
        cutoff = (datetime.now() - timedelta(days=days_lookback)).isoformat()

        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                """
                SELECT session_id, started_at
                FROM rca_sessions
                WHERE problem_hash = ? AND started_at > ?
                ORDER BY started_at DESC
                LIMIT 1
            """,
                (phash, cutoff),
            )

            row = cursor.fetchone()
            if row:
                return row[0]  # Return original session_id

            return None


# Convenience functions for quick usage

_tracker_instance: RCAMetricsTracker | None = None
_tracker_lock = threading.Lock()


def get_metrics_tracker() -> RCAMetricsTracker:
    """Get or create the singleton metrics tracker instance (thread-safe)."""
    global _tracker_instance
    if _tracker_instance is not None:
        return _tracker_instance
    with _tracker_lock:
        if _tracker_instance is None:
            _tracker_instance = RCAMetricsTracker()
    return _tracker_instance


def record_debug_start(
    problem_description: str,
    problem_type: ProblemType = ProblemType.UNKNOWN,
    context: str = "",
) -> str:
    """Quick function to record debug session start."""
    return get_metrics_tracker().record_rca_start(
        problem_description, problem_type, context
    )


def record_chs_search(
    session_id: str, results_count: int, match_type: MatchType
) -> None:
    """Quick function to record CHS results."""
    get_metrics_tracker().record_chs_results(session_id, results_count, match_type)


def record_fix(session_id: str, fix_type: FixType) -> None:
    """Quick function to record fix attempt."""
    get_metrics_tracker().record_fix_attempt(session_id, fix_type)


def record_verification(session_id: str, passed: bool) -> None:
    """Quick function to record verification result."""
    get_metrics_tracker().record_verification(session_id, passed)


def record_delegation_event(
    session_id: str,
    expected_count: int = 1,
    executed_count: int = 0,
    source: str = "rca",
) -> None:
    """Quick function to record delegation KPI event."""
    get_metrics_tracker().record_delegation_event(
        session_id=session_id,
        expected_count=expected_count,
        executed_count=executed_count,
        source=source,
    )


def get_debug_stats(days: int = 30) -> str:
    """Quick function to get formatted stats report."""
    return get_metrics_tracker().get_metrics_report(days)


@dataclass
class MetricAlert:
    """An alert for a metric threshold breach."""

    metric_name: str
    current_value: float
    threshold: float
    severity: str  # "warning", "critical"
    message: str
    action_suggestion: str


class MetricThresholds:
    """
    Threshold definitions for RCA metrics with automated alerts.

    When thresholds are breached, triggers actionable alerts.
    """

    # Threshold format: (warning_level, critical_level, lower_is_better)
    THRESHOLDS = {
        "chs_usage_rate": (90, 80, False),  # Below 90% = warning, below 80% = critical
        "quick_fix_success_rate": (85, 70, False),  # Below 85% = warning
        "fix_verification_rate": (95, 80, False),  # Below 95% = warning
        "recurrence_rate_7d": (8, 15, True),  # Above 8% = warning, above 15% = critical
        "recurrence_rate_30d": (15, 25, True),  # Above 15% = warning
        "avg_time_exact_match": (3, 5, True),  # Above 3min = warning
        "avg_time_new_issue": (12, 20, True),  # Above 12min = warning
        "chs_hit_rate": (50, 40, False),  # Below 50% = warning
    }

    @classmethod
    def check_thresholds(cls, metrics: RCAMetrics) -> list[MetricAlert]:
        """
        Check metrics against thresholds and generate alerts.

        Args:
            metrics: Current metrics to check

        Returns:
            List of MetricAlert for any breached thresholds

        """
        alerts = []

        # Check each metric
        metric_values = {
            "chs_usage_rate": metrics.chs_usage_rate,
            "quick_fix_success_rate": metrics.quick_fix_success_rate,
            "fix_verification_rate": metrics.fix_verification_rate,
            "recurrence_rate_7d": metrics.recurrence_rate_7d,
            "recurrence_rate_30d": metrics.recurrence_rate_30d,
            "avg_time_exact_match": metrics.avg_time_exact_match,
            "avg_time_new_issue": metrics.avg_time_new_issue,
            "chs_hit_rate": metrics.chs_hit_rate,
        }

        for metric_name, value in metric_values.items():
            if metric_name not in cls.THRESHOLDS:
                continue

            warning_thresh, critical_thresh, lower_is_better = cls.THRESHOLDS[metric_name]

            # Determine if threshold is breached
            if lower_is_better:
                # Lower is better (e.g., recurrence rate, time)
                if value >= critical_thresh:
                    alerts.append(MetricAlert(
                        metric_name=metric_name,
                        current_value=value,
                        threshold=critical_thresh,
                        severity="critical",
                        message=f"{metric_name}: {value} (threshold: <{critical_thresh})",
                        action_suggestion=cls._get_action_suggestion(metric_name, "critical")
                    ))
                elif value >= warning_thresh:
                    alerts.append(MetricAlert(
                        metric_name=metric_name,
                        current_value=value,
                        threshold=warning_thresh,
                        severity="warning",
                        message=f"{metric_name}: {value} (threshold: <{warning_thresh})",
                        action_suggestion=cls._get_action_suggestion(metric_name, "warning")
                    ))
            # Higher is better (e.g., success rate, hit rate)
            elif value <= critical_thresh:
                alerts.append(MetricAlert(
                    metric_name=metric_name,
                    current_value=value,
                    threshold=critical_thresh,
                    severity="critical",
                    message=f"{metric_name}: {value}% (threshold: >{critical_thresh}%)",
                    action_suggestion=cls._get_action_suggestion(metric_name, "critical")
                ))
            elif value <= warning_thresh:
                alerts.append(MetricAlert(
                    metric_name=metric_name,
                    current_value=value,
                    threshold=warning_thresh,
                    severity="warning",
                    message=f"{metric_name}: {value}% (threshold: >{warning_thresh}%)",
                    action_suggestion=cls._get_action_suggestion(metric_name, "warning")
                ))

        return alerts

    @classmethod
    def _get_action_suggestion(cls, metric_name: str, severity: str) -> str:
        """Get action suggestion for a metric breach."""
        suggestions = {
            "chs_usage_rate": "CHS not being used consistently - enforce CHS-first policy in /debug workflow",
            "quick_fix_success_rate": "Error signatures may be outdated - refresh pattern database from recent fixes",
            "fix_verification_rate": "Fixes not being verified - enforce test run before marking fix complete",
            "recurrence_rate_7d": "PROBLEMS RECURRING - fixes addressing symptoms not root causes. Use deeper RCA.",
            "recurrence_rate_30d": "High recurrence indicates systemic issues - review fix quality and root cause analysis",
            "avg_time_exact_match": "Quick fixes taking too long - improve error signature matching",
            "avg_time_new_issue": "RCA slow - consider specialist subagent routing for faster resolution",
            "chs_hit_rate": "Historical search not finding matches - may need more indexing or better queries",
        }

        base = suggestions.get(metric_name, "Review this metric for process improvement")

        if severity == "critical":
            return f"🚨 CRITICAL: {base}"
        return f"⚠️ WARNING: {base}"


def check_metric_alerts(days: int = 7) -> list[MetricAlert]:
    """
    Check for metric threshold breaches and return alerts.

    Args:
        days: Number of days to analyze

    Returns:
        List of MetricAlert for any breached thresholds

    """
    tracker = get_metrics_tracker()
    metrics = tracker.get_metrics(days)
    return MetricThresholds.check_thresholds(metrics)


def format_alerts(alerts: list[MetricAlert]) -> str:
    """
    Format metric alerts for display.

    Args:
        alerts: List of MetricAlert

    Returns:
        Formatted alert string

    """
    if not alerts:
        return "✅ All metrics within normal thresholds."

    lines = ["🚨 METRIC ALERTS DETECTED:\n"]

    # Critical alerts first
    critical = [a for a in alerts if a.severity == "critical"]
    warnings = [a for a in alerts if a.severity == "warning"]

    if critical:
        lines.append("## CRITICAL:")
        for alert in critical:
            lines.append(f"  ❌ {alert.message}")
            lines.append(f"     → {alert.action_suggestion}")
        lines.append("")

    if warnings:
        lines.append("## WARNINGS:")
        for alert in warnings:
            lines.append(f"  ⚠️ {alert.message}")
            lines.append(f"     → {alert.action_suggestion}")

    return "\n".join(lines)


def get_metrics_with_alerts(days: int = 7) -> tuple[str, list[MetricAlert]]:
    """
    Get metrics report with alerts.

    Args:
        days: Number of days to analyze

    Returns:
        Tuple of (metrics report string, list of alerts)

    """
    tracker = get_metrics_tracker()
    report = tracker.get_metrics_report(days)
    alerts = check_metric_alerts(days)

    alert_text = format_alerts(alerts)

    return f"{report}\n\n### Threshold Alerts\n\n{alert_text}", alerts



def enforce_verification_gate(
    session_id: str,
    files_changed: list[str],
    bug_type: str = "unknown",
    auto_run: bool = True
) -> dict[str, Any]:
    """
    Enforce the verification gate - fix MUST pass verification to be complete.

    This is the REQUIRED verification step for all fixes in the /debug workflow.

    Args:
        session_id: The RCA session ID
        files_changed: List of files that were modified
        bug_type: Type of bug (error, performance, crash, etc.)
        auto_run: If True, automatically run the verification command

    Returns:
        Dict with verification result and gate status

    Raises:
        Exception: If verification fails and auto_run is True

    """
    import importlib.util
    import subprocess
    import sys
    from pathlib import Path

    # Load post_fix_validator module directly via importlib
    hooks_dir = Path(str(Path(__file__).drive) + "/.claude/hooks")
    validator_path = hooks_dir / "post_fix_validator.py"

    if not validator_path.exists():
        return {
            "success": False,
            "error": "post_fix_validator not found",
            "gate_passed": False,
            "message": f"Verification gate cannot be enforced: {validator_path} not found"
        }

    try:
        # Load module from file path
        spec = importlib.util.spec_from_file_location("post_fix_validator", validator_path)
        if spec is None or spec.loader is None:
            raise ImportError(f"Cannot load module from {validator_path}")
        validator_module = importlib.util.module_from_spec(spec)
        sys.modules["post_fix_validator"] = validator_module
        spec.loader.exec_module(validator_module)

        suggest_fix_verification = validator_module.suggest_fix_verification
        run_fix_verification = validator_module.run_fix_verification
    except (ImportError, AttributeError) as e:
        return {
            "success": False,
            "error": f"post_fix_validator import failed: {e}",
            "gate_passed": False,
            "message": "Verification gate cannot be enforced"
        }

    # Get verification suggestion
    suggestion = suggest_fix_verification(files_changed, bug_type)

    result = {
        "session_id": session_id,
        "files_changed": files_changed,
        "suggested_command": suggestion.get("command"),
        "gate_passed": False,
        "verification_run": False,
    }

    if auto_run and suggestion.get("command"):
        print(f"🔍 Running verification: {suggestion['command']}")

        try:
            verify_result = run_fix_verification(
                suggestion["command"],
                timeout=60 if suggestion.get("estimated_runtime") == "medium" else 30
            )

            result["verification_run"] = True
            result["verification_output"] = verify_result.get("stdout", "")
            result["verification_error"] = verify_result.get("stderr", "")

            if verify_result["success"]:
                result["gate_passed"] = True
                result["success"] = True
                record_verification(session_id, passed=True)
                print("✅ VERIFICATION PASSED - Fix gate cleared")
                return result
            result["success"] = False
            result["error"] = "Verification command failed"
            record_verification(session_id, passed=False)

            error_msg = f"""❌ VERIFICATION GATE FAILED
Command: {suggestion['command']}
Exit code: {verify_result.get('exit_code')}
Output: {verify_result.get('stdout', '')[:200]}
"""
            print(error_msg)
            raise Exception("Verification gate failed - fix not verified")

        except subprocess.TimeoutExpired:
            result["success"] = False
            result["error"] = "Verification timed out"
            record_verification(session_id, passed=False)
            raise Exception("Verification timed out")
    else:
        result["message"] = "Verification gate pending - run command manually"
        result["suggestion"] = suggestion
        return result

    return result


# =============================================================================
# COST CIRCUIT BREAKER - Session Budget Tracking (Week 1 Feature 1.3)
# =============================================================================

@dataclass
class BudgetStatus:
    """Status of session budget tracking."""
    status: str  # "OK", "WARN", "HALT"
    tokens_used: int
    tokens_remaining: int
    budget_pct: float
    reason: str = ""
    action: str = ""


class SessionBudget:
    """
    Cost Circuit Breaker for RCA/debug sessions.

    Tracks token usage across a session and halts when budget exceeded
    or max retries reached. Prevents runaway LLM costs during debugging.

    Example:
        budget = SessionBudget(max_tokens=100_000, max_retries=3)
        budget_check = budget.add_tokens(5000)
        if budget_check.status == "HALT":
            return "Budget exceeded, escalate to human"
    """

    # Approximate token cost: $2.00 ≈ 100,000 tokens at current rates
    DEFAULT_MAX_TOKENS = 100_000
    DEFAULT_MAX_RETRIES = 3

    def __init__(
        self,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        max_retries: int = DEFAULT_MAX_RETRIES
    ):
        """
        Initialize session budget.

        Args:
            max_tokens: Maximum tokens allowed per session (≈$2.00)
            max_retries: Maximum retry attempts before escalation
        """
        self.max_tokens = max_tokens
        self.max_retries = max_retries
        self.session_tokens = 0
        self.retry_count = 0
        self.halted = False
        self.halt_reason = None

    def add_tokens(self, input_tokens: int, output_tokens: int) -> BudgetStatus:
        """
        Track tokens from an LLM interaction.

        Args:
            input_tokens: Input tokens sent to LLM
            output_tokens: Output tokens received from LLM

        Returns:
            BudgetStatus with current state
        """
        if self.halted:
            return BudgetStatus(
                status="HALT",
                tokens_used=self.session_tokens,
                tokens_remaining=0,
                budget_pct=100.0,
                reason=self.halt_reason,
                action="Session already halted - escalate to human"
            )

        total_tokens = input_tokens + output_tokens
        self.session_tokens += total_tokens
        remaining = self.max_tokens - self.session_tokens
        budget_pct = (self.session_tokens / self.max_tokens) * 100

        # Check if budget exceeded
        if remaining < 0:
            self.halted = True
            self.halt_reason = "Budget exceeded"
            return BudgetStatus(
                status="HALT",
                tokens_used=self.session_tokens,
                tokens_remaining=0,
                budget_pct=100.0,
                reason="Budget exceeded",
                action=f"Escalate to human - used {self.session_tokens:,} tokens"
            )

        # Warning at 80% budget
        if budget_pct >= 80:
            return BudgetStatus(
                status="WARN",
                tokens_used=self.session_tokens,
                tokens_remaining=remaining,
                budget_pct=budget_pct,
                reason="Approaching budget limit",
                action=f"Consider escalation - {budget_pct:.1f}% budget used"
            )

        return BudgetStatus(
            status="OK",
            tokens_used=self.session_tokens,
            tokens_remaining=remaining,
            budget_pct=budget_pct
        )

    def increment_retry(self) -> BudgetStatus:
        """
        Track a retry attempt.

        Returns:
            BudgetStatus with current state
        """
        if self.halted:
            return BudgetStatus(
                status="HALT",
                tokens_used=self.session_tokens,
                tokens_remaining=self.max_tokens - self.session_tokens,
                budget_pct=(self.session_tokens / self.max_tokens) * 100,
                reason=self.halt_reason,
                action="Session already halted"
            )

        self.retry_count += 1
        remaining_retries = self.max_retries - self.retry_count

        # Check if max retries exceeded
        if self.retry_count > self.max_retries:
            self.halted = True
            self.halt_reason = "Max retries exceeded"
            return BudgetStatus(
                status="HALT",
                tokens_used=self.session_tokens,
                tokens_remaining=self.max_tokens - self.session_tokens,
                budget_pct=(self.session_tokens / self.max_tokens) * 100,
                reason="Max retries exceeded",
                action="Problem too complex - escalate to human developer"
            )

        # Warning at last retry
        if remaining_retries == 0:
            return BudgetStatus(
                status="WARN",
                tokens_used=self.session_tokens,
                tokens_remaining=self.max_tokens - self.session_tokens,
                budget_pct=(self.session_tokens / self.max_tokens) * 100,
                reason="Last retry",
                action="Final attempt - consider escalation if this fails"
            )

        return BudgetStatus(
            status="OK",
            tokens_used=self.session_tokens,
            tokens_remaining=self.max_tokens - self.session_tokens,
            budget_pct=(self.session_tokens / self.max_tokens) * 100
        )

    def get_summary(self) -> dict:
        """Get summary of current budget state."""
        return {
            "tokens_used": self.session_tokens,
            "tokens_remaining": max(0, self.max_tokens - self.session_tokens),
            "budget_pct": (self.session_tokens / self.max_tokens) * 100,
            "retries_used": self.retry_count,
            "retries_remaining": max(0, self.max_retries - self.retry_count),
            "halted": self.halted,
            "halt_reason": self.halt_reason
        }

    def reset(self) -> None:
        """Reset budget tracking (use with caution)."""
        self.session_tokens = 0
        self.retry_count = 0
        self.halted = False
        self.halt_reason = None


# Session budget management for CWO12/RCA workflows
_session_budget: SessionBudget | None = None
_session_budget_lock = threading.Lock()


def get_session_budget() -> SessionBudget:
    """Get or create the session budget instance (thread-safe)."""
    global _session_budget
    if _session_budget is not None:
        return _session_budget
    with _session_budget_lock:
        if _session_budget is None:
            _session_budget = SessionBudget()
    return _session_budget


def reset_session_budget() -> None:
    """Reset the session budget (call when starting new debug session)."""
    global _session_budget
    with _session_budget_lock:
        _session_budget = SessionBudget()


def track_llm_tokens(input_tokens: int, output_tokens: int) -> BudgetStatus:
    """
    Track LLM token usage for current session.

    Convenience function for quick token tracking.

    Args:
        input_tokens: Input tokens sent to LLM
        output_tokens: Output tokens received from LLM

    Returns:
        BudgetStatus with current budget state
    """
    return get_session_budget().add_tokens(input_tokens, output_tokens)


def track_retry_attempt() -> BudgetStatus:
    """
    Track a retry attempt in current session.

    Returns:
        BudgetStatus with current budget state
    """
    return get_session_budget().increment_retry()


def is_session_halted() -> bool:
    """Check if session has been halted due to budget/retry limit."""
    budget = get_session_budget()
    return budget.halted


def get_budget_summary() -> dict:
    """Get summary of current session budget."""
    return get_session_budget().get_summary()



    # Test recording a session
    session_id = tracker.record_rca_start(
        "ImportError: No module named 'test_module'",
        ProblemType.ERROR,
        "import statement in main.py",
    )
    print(f"Created session: {session_id}")

    # Test CHS results
    tracker.record_chs_results(session_id, 3, MatchType.EXACT)
    tracker.record_cks_results(session_id, 2)

    # Test fix
    tracker.record_fix_attempt(session_id, FixType.QUICK_FIX)

    # Test verification
    tracker.record_verification(session_id, True)

    # Get metrics
    print(tracker.get_metrics_report(30))


if __name__ == "__main__":
    # Self-test
    tracker = RCAMetricsTracker()

    # Test recording a session
    session_id = tracker.record_rca_start(
        "ImportError: No module named 'test_module'",
        ProblemType.ERROR,
        "import statement in main.py",
    )
    print(f"Created session: {session_id}")

    # Test CHS results
    tracker.record_chs_results(session_id, 3, MatchType.EXACT)
    tracker.record_cks_results(session_id, 2)

    # Test fix
    tracker.record_fix_attempt(session_id, FixType.QUICK_FIX)

    # Test verification
    tracker.record_verification(session_id, True)

    # Get metrics
    print(tracker.get_metrics_report(30))

    # Test SessionBudget (Week 1 Feature 1.3)
    print("\n=== Testing SessionBudget (Cost Circuit Breaker) ===")
    budget = SessionBudget(max_tokens=1000, max_retries=2)

    # Add tokens
    status = budget.add_tokens(100, 200)
    print(f"Status: {status.status}, Used: {status.tokens_used}, Remaining: {status.tokens_remaining}")

    # Approaching limit
    status = budget.add_tokens(400, 100)
    print(f"Status: {status.status}, Budget: {status.budget_pct:.1f}%")

    # Exceed limit
    status = budget.add_tokens(100, 200)
    print(f"Status: {status.status}, Reason: {status.reason}")

    # Test retries
    print("\n=== Testing Retry Tracking ===")
    budget2 = SessionBudget(max_retries=2)
    print(f"Retry 1: {budget2.increment_retry().status}")
    print(f"Retry 2: {budget2.increment_retry().status}")
    print(f"Retry 3 (should halt): {budget2.increment_retry().status}")
