"""
Modern cookie extraction using rookiepy library.

This addresses the DPAPI encryption issues mentioned in the user's guide
and provides a more reliable alternative to the Playwright approach.
"""

import logging
from typing import Any

from rich.console import Console

try:
    from http.cookiejar import CookieJar

    import requests
    import rookiepy
    ROOKIE_AVAILABLE = True
except ImportError:
    ROOKIE_AVAILABLE = False

class ModernCookieExtractor:
    """Modern cookie extraction using rookiepy library."""

    def __init__(self, console: Console | None = None):
        """
        Initialize the modern cookie extractor.

        Args:
            console: Rich console instance for output (defaults to new Console())
        """
        self.console = console or Console()
        self.logger = logging.getLogger(__name__)

    def create_cookiejar(self, cookies: list[dict[str, Any]]) -> CookieJar:
        """Convert rookiepy list of dicts to a requests.CookieJar."""
        jar = CookieJar()
        for cookie in cookies:
            try:
                jar.set_cookie(requests.cookies.create_cookie(
                    domain=cookie["domain"],
                    name=cookie["name"],
                    value=cookie["value"],
                    path=cookie.get("path", "/"),
                    secure=cookie.get("secure", False),
                    expires=cookie.get("expires")
                ))
            except Exception:
                self.logger.debug("Failed to process cookie %s: {e}", cookie.get("name", "unknown"))
        return jar

    def extract_cookies(self, browser: str = "chrome", domains: list[str] | None = None) -> str | None:
        """
        Extract cookies using rookiepy and save to file.

        Args:
            browser: 'chrome', 'firefox', 'edge', or 'safari'
            domains: List of domains to filter for (default: youtube.com)

        Returns:
            Path to cookie file or None if extraction failed
        """
        if not ROOKIE_AVAILABLE:
            self.console.print("[red]❌ rookiepy not installed[/red]")
            self.console.print("[yellow]→ Install with: pip install rookiepy requests[/yellow]")
            return None

        if domains is None:
            domains = ["youtube.com", ".youtube.com"]

        browser_methods = {
            "chrome": rookiepy.chrome,
            "firefox": rookiepy.firefox,
            "edge": rookiepy.edge,
            "safari": rookiepy.safari
        }

        if browser.lower() not in browser_methods:
            self.console.print(f"[red]❌ Unsupported browser: {browser}[/red]")
            self.console.print("[yellow]→ Supported: chrome, firefox, edge, safari[/yellow]")
            return None

        try:
            self.console.print(f"[blue]🔧 Extracting {browser} cookies with rookiepy...[/blue]")

            # Extract cookies using rookiepy
            cookies = browser_methods[browser.lower()](domains)

            if not cookies:
                self.console.print(f"[yellow]⚠️ No cookies found for {browser}[/yellow]")
                return None

            self.console.print(f"[green]✅ Found {len(cookies)} cookies[/green]")

            # Save to file in yt-dlp compatible format
            import tempfile

            temp_file = tempfile.NamedTemporaryFile(
                mode="w",
                suffix=".txt",
                delete=False,
                prefix=f"yt_cookies_{browser.lower()}_"
            )

            # Write in Netscape format
            temp_file.write("# Netscape HTTP Cookie File\n")
            temp_file.write(f"# Generated by rookiepy from {browser}\n")
            temp_file.write(f"# YouTube cookies: {len(cookies)}\n\n")

            for cookie in cookies:
                # Convert to Netscape format
                domain_flag = "TRUE" if cookie.get("domain", "").startswith(".") else "FALSE"
                expires = str(int(cookie.get("expires", 0))) if cookie.get("expires") else "0"

                line = "\t".join([
                    cookie.get("domain", ""),
                    domain_flag,
                    cookie.get("path", "/"),
                    "TRUE" if cookie.get("secure", False) else "FALSE",
                    expires,
                    cookie.get("name", ""),
                    cookie.get("value", "")
                ])
                temp_file.write(line + "\n")

            temp_file.close()

            self.console.print(f"[green]✅ Cookies saved to: {temp_file.name}[/green]")
            return temp_file.name

        except PermissionError:
            self.console.print(f"[yellow]⚠️ {browser.title()} access denied[/yellow]")
            self.console.print("[yellow]→ Close {browser} and try again[/yellow]")
            return None

        except Exception as e:
            error_str = str(e).lower()
            if "no such file" in error_str:
                self.console.print(f"[yellow]⚠️ {browser.title()} not found or not installed[/yellow]")
            elif "permission" in error_str:
                self.console.print(f"[yellow]⚠️ {browser.title()} access denied[/yellow]")
                self.console.print("[yellow]→ Close {browser} and try again[/yellow]")
            else:
                self.console.print("[red]❌ Cookie extraction failed[/red]")
                # ROOKIE_AVAILABLE is always True here (we return early if False at line 65)
                self.console.print(f"[yellow]→ {error_str[:100]}[/yellow]")

            self.logger.error("rookiepy extraction error: %s", e, exc_info=True)
            return None

    def test_cookies(self, cookie_file: str) -> bool:
        """Test if cookies work by making a request to YouTube."""
        try:
            import yt_dlp

            ydl_opts = {
                "quiet": True,
                "no_warnings": True,
                "cookiefile": cookie_file,
                "extract_flat": True,
            }

            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                result = ydl.extract_info(
                    "https://www.youtube.com/@TwoMinutePapers",
                    download=False,
                    process=False
                )

                if result and "title" in result:
                    self.console.print(f"[green]✅ Cookies working: {result.get('title', 'Unknown')}[/green]")
                    return True

        except Exception as e:
            self.console.print(f"[yellow]⚠️ Cookie test failed: {str(e)[:100]}[/yellow]")

        return False

def install_rookiepy() -> bool:
    """Install rookiepy and dependencies."""
    import subprocess
    import sys

    console = Console()
    console.print("[blue]📦 Installing rookiepy for modern cookie extraction...[/blue]")

    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "rookiepy", "requests"])
        console.print("[green]✅ rookiepy installed successfully[/green]")
        return True
    except subprocess.CalledProcessError as e:
        console.print(f"[red]❌ Installation failed: {e}[/red]")
        return False
