#!/usr/bin/env python3
"""
PostToolUse transition for /refactor skill.
Advances workflow phase after successful step completion.
Appends STEP_COMPLETE to execution ledger on phase advance.
Auto-generated by /av improve /refactor
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from state_manager_refactor import write_state, read_state, advance_if_complete, append_ledger, PHASES

# Phase → ledger step name mapping
PHASE_TO_STEP = {
    "PREFLIGHT": "PREFLIGHT",
    "DISCOVERY": "DISCOVER",
    "PLANNING": "PLAN",
    "EXECUTION": "REFACTOR",
}


def main():
    input_data = json.loads(sys.stdin.read())
    tool_name = input_data.get("tool_name", "")
    tool_output = input_data.get("tool_output", "") or ""
    tool_input = input_data.get("tool_input", {})

    state = read_state()
    if not state:
        sys.exit(0)  # No active state, nothing to transition

    current_phase = state.get("phase", "")
    session_id = state.get("session_id")

    # Collect evidence about what was accomplished
    evidence = dict(state.get("evidence", {}))

    # Update evidence based on tool results
    if tool_name == "Bash" and "complexity_scanner" in tool_output:
        evidence["complexity_scan_done"] = True
    if tool_name == "Bash" and "deduplicate" in tool_output:
        artifacts_dir = tool_input.get("artifacts_dir", "")
        if artifacts_dir:
            evidence["artifacts_dir"] = artifacts_dir
    if tool_name == "Bash" and "refactor_plan" in tool_output:
        artifacts_dir = tool_input.get("artifacts_dir", "")
        if artifacts_dir:
            evidence["plan_created"] = True
    if tool_name == "Bash" and "adversarial_review" in tool_output.lower():
        artifacts_dir = tool_input.get("artifacts_dir", "")
        if artifacts_dir:
            evidence["review_done"] = True
    if tool_name == "Bash" and "git tag" in tool_output.lower():
        evidence["checkpoint_created"] = True
    if tool_name == "Bash" and ("pytest" in tool_output or "test" in tool_output):
        if "0 failed" in tool_output or "passed" in tool_output.lower():
            evidence["all_tests_pass"] = True

    # Try to advance phase if criteria are met
    next_phase = advance_if_complete(current_phase, evidence)

    if next_phase:
        # Append STEP_COMPLETE for the phase being exited
        step_name = PHASE_TO_STEP.get(current_phase, current_phase)
        append_ledger(step_name, "STEP_COMPLETE", session_id)

        if next_phase == "DONE":
            # Final REFACTOR step complete
            append_ledger("REFACTOR", "STEP_COMPLETE", session_id)
        else:
            next_config = PHASES.get(next_phase, {})
            new_session_id = write_state(
                phase=next_phase,
                allowed_tools=next_config.get("allowed_tools", []),
                evidence=evidence,
                expires_in=600
            )
            # STEP_START for the new phase
            append_ledger(next_phase, "STEP_START", new_session_id)

    sys.exit(0)


if __name__ == "__main__":
    main()