#!/usr/bin/env python3
"""
State manager for /refactor workflow phase sequencing.
Auto-generated by /av improve /refactor

Phase tracking: PREFLIGHT -> DISCOVERY -> PLANNING -> EXECUTION
Each phase must complete its success criteria before advancing.
Supports 3-store architecture: phase_state (gating), execution_ledger (trace), session_artifacts (evidence).
"""
from pathlib import Path
import hashlib
import json
import time
import uuid

instance_id = hashlib.md5(str(Path.cwd()).encode()).hexdigest()[:8]
STATE_DIR = Path("P:\\\\\\.claude/hooks/state")
STATE_FILE = STATE_DIR / f"refactor_{instance_id}.json"
LEDGER_FILE = STATE_DIR / f"refactor_{instance_id}_ledger.jsonl"

# Phase definitions with allowed tools and completion criteria
PHASES = {
    "PREFLIGHT": {
        "next": "DISCOVERY",
        "allowed_tools": ["Grep", "Read", "Bash"],
        "completion_criteria": "migration_shim_verified OR no_migration_detected",
        "evidence_required": ["shim_path", "caller_count"]  # for migration type
    },
    "DISCOVERY": {
        "next": "PLANNING",
        "allowed_tools": ["Task", "Bash", "Grep", "Read"],
        "completion_criteria": "deduplicated.json exists AND findings_count > 0",
        "evidence_required": ["artifacts_dir/refactor/deduplicated.json"]
    },
    "PLANNING": {
        "next": "EXECUTION",
        "allowed_tools": ["Bash", "Read", "Write"],
        "completion_criteria": "plan.json exists AND adversarial_review_passed",
        "evidence_required": ["artifacts_dir/refactor/plan.json", "adversarial_review_output"]
    },
    "EXECUTION": {
        "next": "DONE",
        "allowed_tools": ["Edit", "Write", "Bash", "Task", "Read", "Grep"],
        "completion_criteria": "all_tests_pass AND quality_score_recorded",
        "evidence_required": [
            "git_tag_refactor_green_* exists",
            "regression_output (0 failures)",
            "deletion_metric (positive or justified)"
        ]
    }
}

def write_state(phase: str, allowed_tools: list, evidence: dict = None, expires_in: int = 600):
    """Write workflow state with expiration and evidence tracking. Generates session_id on first call."""
    existing = read_state()
    session_id = existing.get("session_id") if existing else None
    if not session_id:
        session_id = uuid.uuid4().hex[:12]

    state = {
        "phase": phase,
        "allowed_tools": allowed_tools,
        "expires_at": time.time() + expires_in,
        "skill": "refactor",
        "instance": instance_id,
        "session_id": session_id,
        "evidence": evidence or {},
        "step_started_at": time.time()
    }
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)

    if not existing:
        append_ledger(phase, "STEP_START", session_id)

    return session_id


def append_ledger(step: str, event: str, session_id: str = None):
    """Append an immutable entry to the execution ledger."""
    if session_id is None:
        state = read_state()
        session_id = state.get("session_id") if state else "unknown"

    entry = {
        "session_id": session_id,
        "step": step,
        "event": event,
        "ts": time.time()
    }
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    with open(LEDGER_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")

def read_state() -> dict | None:
    """Read state if exists and not expired."""
    if not STATE_FILE.exists():
        return None
    try:
        with open(STATE_FILE) as f:
            state = json.load(f)
        if time.time() > state.get("expires_at", 0):
            STATE_FILE.unlink()
            return None
        return state
    except (json.JSONDecodeError, OSError):
        return None

def clear_state():
    """Remove state file."""
    if STATE_FILE.exists():
        STATE_FILE.unlink()

def get_current_phase_evidence(phase: str) -> dict:
    """Return expected evidence keys for a given phase."""
    if phase not in PHASES:
        return {}
    return {"required_evidence": PHASES[phase]["evidence_required"]}

def advance_if_complete(current_phase: str, evidence: dict) -> str | None:
    """
    Check if completion criteria are met for current phase.
    If met, return next phase (caller should call write_state with next phase).
    If not met, return None (stay in current phase).
    """
    if current_phase not in PHASES:
        return None

    phase_config = PHASES[current_phase]
    criteria = phase_config["completion_criteria"]

    # Simple criteria check - in production this would be more sophisticated
    if current_phase == "PREFLIGHT":
        # PREFLIGHT completes when migration type is determined
        if "migration_detected" in evidence or "no_migration" in evidence:
            return phase_config["next"]
    elif current_phase == "DISCOVERY":
        # DISCOVERY completes when deduplicated.json exists
        artifacts_dir = evidence.get("artifacts_dir", "")
        if artifacts_dir and Path(artifacts_dir).joinpath("refactor", "deduplicated.json").exists():
            return phase_config["next"]
    elif current_phase == "PLANNING":
        # PLANNING completes when plan.json exists AND adversarial review passed
        artifacts_dir = evidence.get("artifacts_dir", "")
        if artifacts_dir:
            plan_path = Path(artifacts_dir).joinpath("refactor", "plan.json")
            if plan_path.exists():
                # Check adversarial review passed
                review_path = Path(artifacts_dir).joinpath("refactor", "adversarial_review.json")
                if review_path.exists():
                    try:
                        with open(review_path) as f:
                            review = json.load(f)
                        if review.get("passed", False):
                            return phase_config["next"]
                    except (json.JSONDecodeError, OSError):
                        pass
    elif current_phase == "EXECUTION":
        # EXECUTION completes when all completion criteria met
        if evidence.get("all_tests_pass") and evidence.get("quality_score_recorded"):
            return phase_config["next"]

    return None