#!/usr/bin/env python3
"""
Stop verifier for /refactor skill.
Checks execution ledger and artifacts to determine if STOP is safe.
Returns structured JSON verdict: {"can_stop": true/false, "blocking_gaps": [...]}.
Auto-generated by /av improve /refactor
"""
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from state_manager_refactor import read_state, LEDGER_FILE, STATE_DIR, instance_id

REQUIRED_STEPS = ["PREFLIGHT", "DISCOVER", "PLAN", "REFACTOR"]


def get_git_tags() -> list[str]:
    """Get all git tags."""
    try:
        result = subprocess.run(
            ["git", "tag", "--list", "refactor/*"],
            capture_output=True, text=True, timeout=10
        )
        return result.stdout.strip().split("\n") if result.stdout.strip() else []
    except (subprocess.TimeoutExpired, OSError):
        return []


def read_ledger_entries(session_id: str) -> list[dict]:
    """Read ledger entries for a given session_id."""
    if not LEDGER_FILE.exists():
        return []
    entries = []
    with open(LEDGER_FILE) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                if entry.get("session_id") == session_id:
                    entries.append(entry)
            except json.JSONDecodeError:
                continue
    return entries


def get_artifacts_dir(state: dict) -> Path:
    """Resolve artifacts directory from state or default."""
    evidence = state.get("evidence", {})
    artifacts_dir = evidence.get("artifacts_dir", "")
    if artifacts_dir:
        return Path(artifacts_dir)
    return Path(f"P:/.claude/.artifacts/{state.get('instance', instance_id)}/refactor")


def check_artifacts(state: dict) -> list[str]:
    """Check required artifacts exist and return list of gaps."""
    gaps = []
    artifacts_dir = get_artifacts_dir(state)

    # DISCOVERY: deduplicated.json
    dedup_path = artifacts_dir / "deduplicated.json"
    if not dedup_path.exists():
        gaps.append(f"deduplicated.json not found at {dedup_path}")

    # PLANNING: plan.json
    plan_path = artifacts_dir / "plan.json"
    if not plan_path.exists():
        gaps.append(f"plan.json not found at {plan_path}")

    # ADVERSARIAL_REVIEW: adversarial_review.json with passed=true
    review_path = artifacts_dir / "adversarial_review.json"
    if not review_path.exists():
        gaps.append(f"adversarial_review.json not found at {review_path}")
    else:
        try:
            with open(review_path) as f:
                review = json.load(f)
            if not review.get("passed"):
                gaps.append("adversarial_review.json exists but passed=false")
        except json.JSONDecodeError:
            gaps.append(f"adversarial_review.json is malformed")

    # CHECKPOINT_GREEN: refactor/green-* git tag
    tags = get_git_tags()
    green_tags = [t for t in tags if t.startswith("refactor/green-")]
    if not green_tags:
        gaps.append("No refactor/green-* git tag found")

    # REGRESSION: check test results in evidence
    if not state.get("evidence", {}).get("all_tests_pass"):
        gaps.append("No evidence that regression tests passed")

    return gaps


def verify(state: dict) -> dict:
    """Run verification and return structured verdict."""
    session_id = state.get("session_id", "")

    # Check ledger entries
    entries = read_ledger_entries(session_id) if session_id else []
    completed_steps = {e["step"] for e in entries if e["event"] == "STEP_COMPLETE"}

    missing_steps = [s for s in REQUIRED_STEPS if s not in completed_steps]

    # Check artifacts
    artifact_gaps = check_artifacts(state)

    all_gaps = missing_steps + artifact_gaps
    can_stop = len(all_gaps) == 0

    verdict = {
        "can_stop": can_stop,
        "session_id": session_id,
        "phase": state.get("phase", "unknown"),
        "completed_steps": sorted(completed_steps),
        "missing_steps": missing_steps,
        "artifact_gaps": artifact_gaps,
        "blocking_gaps": all_gaps,
    }

    return verdict


def main():
    input_data = json.loads(sys.stdin.read())

    state = read_state()
    if not state:
        # No active state - allow stop, skill may have completed cleanly
        verdict = {
            "can_stop": True,
            "session_id": None,
            "phase": "unknown",
            "completed_steps": [],
            "missing_steps": [],
            "artifact_gaps": [],
            "blocking_gaps": [],
            "note": "No active state found"
        }
        print(json.dumps(verdict))
        sys.exit(0)
        return

    verdict = verify(state)
    print(json.dumps(verdict))
    sys.exit(0 if verdict["can_stop"] else 1)


if __name__ == "__main__":
    main()
