#\!/usr/bin/env python3
"""Save CKS entries from auto-commit hook reflection session.

Saves 5 lessons from the reflection on auto-commit CHANGELOG timing fix.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add __csf to path
csf_path = Path("P:/__csf").resolve()
if str(csf_path) not in sys.path:
    sys.path.insert(0, str(csf_path))

# Try to import store_to_cks with fallback
store_to_cks = None

# Method 1: Import from retrospective_common
try:
    sys.path.insert(0, str(csf_path / "src"))
    sys.path.insert(0, str(csf_path / "src" / "core"))
    from retrospective_common import store_to_cks as store_fn
    store_to_cks = store_fn
    print("✓ Imported store_to_cks from retrospective_common")
except Exception as e:
    print(f"✗ Failed to import from retrospective_common: {e}")

# Method 2: Direct CKS implementation
if not store_to_cks:
    try:
        from datetime import datetime, UTC
        from src.knowledge.systems.cks.unified import ingest_pattern

        if ingest_pattern:
            def store_to_cks_direct(text: str, category: str, score: int, session_id: str | None = None, chs_references: list[str] | None = None) -> str | None:
                """Direct implementation using ingest_pattern."""
                title = f"Lesson: {category}"
                content = f"Pattern: {text}. Category: {category}. Score: {score}."

                metadata = {
                    "source": "reflection_cks_script",
                    "last_accessed": datetime.now(UTC).isoformat(),
                }

                if session_id:
                    metadata["session_id"] = session_id
                if chs_references:
                    metadata["chs_references"] = chs_references

                return ingest_pattern(
                    title=title,
                    content=content,
                    metadata=metadata,
                    entry_type="pattern"
                )

            store_to_cks = store_to_cks_direct
            print("✓ Using direct CKS implementation")
    except Exception as e:
        print(f"✗ Direct CKS implementation failed: {e}")

if not store_to_cks:
    print("ERROR: store_to_cks function not available")
    sys.exit(1)

# CKS entries from reflection
CKS_ENTRIES = [
    {
        "text": "Stop event triggers after every response completes, not at session end. Stop event timing: after every response, not session termination.",
        "category": "hook_events",
        "score": 90,
        "session_id": None,
        "chs_references": None
    },
    {
        "text": "CHANGELOG generation already existed via change_analyzer.py. Always check existing implementations before adding features. Feature discovery prevents duplicate work.",
        "category": "process",
        "score": 80,
        "session_id": None,
        "chs_references": None
    },
    {
        "text": "Files generated by commit process must be updated BEFORE git commit to be included. Git commit flow: Update CHANGELOG → Stage → Commit (not Commit → Update → Re-stage).",
        "category": "workflow",
        "score": 80,
        "session_id": None,
        "chs_references": None
    },
    {
        "text": "User correction repetition pattern: Repeated same error 3+ times despite correction. When corrected, update mental model immediately - don't repeat mistakes. Stop event timing corrected multiple times.",
        "category": "process",
        "score": 80,
        "session_id": None,
        "chs_references": None
    },
    {
        "text": "Auto-commit hook architecture: change_analyzer.py provides analyze_changes(), update_changelog(), changelog_already_changed(). Located at P:/.claude/hooks/change_analyzer.py",
        "category": "architecture",
        "score": 60,
        "session_id": None,
        "chs_references": None
    }
]


def main() -> int:
    """Save all CKS entries and report results."""
    print("Saving CKS entries from auto-commit hook reflection...")
    print()

    saved_count = 0
    failed_count = 0
    entry_ids = []

    for i, entry in enumerate(CKS_ENTRIES, 1):
        print(f"Entry {i}/5: {entry["category"]}")

        try:
            entry_id = store_to_cks(
                text=entry["text"],
                category=entry["category"],
                score=entry["score"],
                session_id=entry.get("session_id"),
                chs_references=entry.get("chs_references")
            )

            if entry_id:
                print(f"  ✓ Saved: {entry_id}")
                entry_ids.append(entry_id)
                saved_count += 1
            else:
                print(f"  ✗ Skipped (CKS unavailable)")
                failed_count += 1

        except Exception as e:
            print(f"  ✗ Failed: {e}")
            failed_count += 1

        print()

    print("=" * 60)
    print(f"Results: {saved_count} saved, {failed_count} failed")

    if entry_ids:
        print(f"Entry IDs: {", ".join(entry_ids)}")

    print("=" * 60)

    return 0 if failed_count == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
