#!/usr/bin/env python3
"""
StopHook for /tdd - Blocks stopping until workflow complete.
Auto-generated by /av2.

Exit codes:
- 0: Allow stop (workflow complete or at explicit halt gate)
- 2: BLOCK stop (workflow incomplete, forces continuation)
"""

import json
import sys
from pathlib import Path

# Add hooks directory to path for terminal detection
hooks_dir = Path("P:/.claude/hooks")
if str(hooks_dir) not in sys.path:
    sys.path.insert(0, str(hooks_dir))

from terminal_detection import detect_terminal_id


def _get_state_file() -> Path:
    """Get terminal-isolated state file path."""
    terminal_id = detect_terminal_id()
    state_dir = Path.home() / ".claude" / ".state" / "tdd" / terminal_id
    state_dir.mkdir(parents=True, exist_ok=True)
    return state_dir / "tdd_workflow.json"


def read_state() -> dict | None:
    state_file = _get_state_file()
    if not state_file.exists():
        return None
    try:
        return json.loads(state_file.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def main():
    try:
        payload = json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        payload = {}

    state = read_state()

    # No workflow active - allow stop
    if state is None:
        sys.exit(0)

    # Workflow explicitly halted at gate - allow stop
    if state.get("halted", False):
        sys.exit(0)

    # Workflow complete - allow stop
    if state.get("complete", False):
        sys.exit(0)

    current = state.get("current_stage", 0)
    max_stage = state.get("max_stage", 6)
    stages = {
        1: "DISCOVER",
        2: "RED",
        3: "GREEN",
        4: "VERIFY",
        5: "REGRESSION",
        6: "REFACTOR",
    }

    # Workflow incomplete - BLOCK stop
    if current < max_stage:
        next_stage = current + 1
        next_name = stages.get(next_stage, f"Stage {next_stage}")

        msg = "🔴 BLOCKED: /tdd workflow incomplete.\n"
        msg += f"Current: Stage {current}\n"
        msg += f"MANDATORY: Execute Stage {next_stage} ({next_name}) NOW.\n"
        msg += "Do NOT stop until all stages complete or an explicit HALT gate is reached."

        print(msg, file=sys.stderr)
        sys.exit(2)  # ← BLOCKS Claude from stopping

    sys.exit(0)


if __name__ == "__main__":
    main()
