#!/usr/bin/env python3
"""
Unit tests for Tier 0 checklist integration in /verify verifier.

Tests follow TDD approach: define expected behavior first, then implement.
"""

import sys
from pathlib import Path
from unittest.mock import patch

import pytest

# Add skill root to path for imports
skill_root = Path(__file__).parent.parent
sys.path.insert(0, str(skill_root))


class TestTier0ChecklistIntegration:
    """Test Tier 0 checklist integration in verify workflow."""

    def test_verifier_has_run_tier0_checklist_method(self):
        """Test that Verifier class has run_tier0_checklist method."""
        from core.verifier import Verifier

        verifier = Verifier()

        # Check method exists
        assert hasattr(verifier, "run_tier0_checklist"), (
            "Verifier should have run_tier0_checklist method"
        )

        # Check it's callable
        assert callable(verifier.run_tier0_checklist), "run_tier0_checklist should be callable"

    @patch("core.verifier.run_checklist_verification")
    def test_run_tier0_checklist_for_skill(self, mock_checklist):
        """Test running Tier 0 checklist for a skill target."""
        from core.verifier import Verifier

        # Mock successful checklist verification
        mock_checklist.return_value = {
            "status": "pass",
            "items_checked": 5,
            "items_passed": 5,
            "findings": [
                "✓ SKILL.md exists",
                "✓ Has name field",
                "✓ Has description field",
                "✓ Has triggers",
                "✓ Has workflow_steps",
            ],
        }

        verifier = Verifier()
        result = verifier.run_tier0_checklist("skill", "arch")

        # Verify checklist was called with correct arguments (path is generated by _get_target_path)
        mock_checklist.assert_called_once_with("skill", "P:/.claude/skills/arch")

        # Verify result structure
        assert result["status"] == "pass"
        assert result["items_checked"] == 5
        assert result["items_passed"] == 5
        assert len(result["findings"]) == 5

    @patch("core.verifier.run_checklist_verification")
    def test_run_tier0_checklist_for_hook(self, mock_checklist):
        """Test running Tier 0 checklist for a hook target."""
        from core.verifier import Verifier

        # Mock partial checklist verification
        mock_checklist.return_value = {
            "status": "partial",
            "items_checked": 4,
            "items_passed": 3,
            "findings": [
                "✓ Hook file exists",
                "✓ Has main() function",
                "✗ Missing docstring",
                "✓ Has type hints",
            ],
        }

        verifier = Verifier()
        result = verifier.run_tier0_checklist("hook", "breadcrumb_init")

        # Verify checklist was called (path is generated by _get_target_path)
        mock_checklist.assert_called_once_with("hook", "P:/.claude/hooks/*breadcrumb_init*.py")

        # Verify partial status
        assert result["status"] == "partial"
        assert result["items_checked"] == 4
        assert result["items_passed"] == 3

    @patch("core.verifier.run_checklist_verification")
    def test_run_tier0_checklist_for_feature(self, mock_checklist):
        """Test running Tier 0 checklist for a feature target."""
        from core.verifier import Verifier

        # Mock failed checklist verification
        mock_checklist.return_value = {
            "status": "fail",
            "items_checked": 3,
            "items_passed": 0,
            "findings": ["✗ Feature not documented", "✗ No tests found", "✗ No integration points"],
        }

        verifier = Verifier()
        result = verifier.run_tier0_checklist("feature", "e2e")

        # Verify checklist was called
        mock_checklist.assert_called_once_with("feature", "e2e")

        # Verify fail status
        assert result["status"] == "fail"
        assert result["items_passed"] == 0

    @patch("core.verifier.run_checklist_verification")
    def test_run_tier0_checklist_invalid_target_type(self, mock_checklist):
        """Test that invalid target type raises ValueError."""
        from core.verifier import Verifier

        # Mock to raise ValueError for invalid type
        mock_checklist.side_effect = ValueError("Invalid target type: invalid_type")

        verifier = Verifier()

        with pytest.raises(ValueError, match="Invalid target type"):
            verifier.run_tier0_checklist("invalid_type", "some_target")


class TestTier0FastFailLogic:
    """Test fast-fail logic when Tier 0 checklist fails."""

    @patch("core.verifier.Tier3E2E")
    @patch("core.verifier.Tier2Integration")
    @patch("core.verifier.Tier1Component")
    def test_tier0_fail_blocks_tier1_execution(self, mock_tier1, mock_tier2, mock_tier3):
        """Test that Tier 0 failure prevents Tier 1 from running."""
        from core.verifier import Verifier

        # Mock Tier 0 failing
        with patch.object(Verifier, "run_tier0_checklist") as mock_tier0:
            mock_tier0.return_value = {
                "status": "fail",
                "items_checked": 5,
                "items_passed": 1,
                "findings": ["✗ Missing critical items"],
            }

            verifier = Verifier()
            report = verifier.verify("skill:arch")

            # Tier 0 should be in report
            assert "tier0" in report
            assert report["tier0"]["status"] == "fail"

            # Overall status should be failed
            assert report["overall_status"] == "failed"

            # Tier 1, 2, 3 should not have been called (fast-fail)
            mock_tier1.return_value.run_tests.assert_not_called()
            mock_tier2.return_value.check_integration.assert_not_called()
            mock_tier3.return_value.check_e2e.assert_not_called()

    @patch("core.verifier.Tier3E2E")
    @patch("core.verifier.Tier2Integration")
    @patch("core.verifier.Tier1Component")
    def test_tier0_partial_allows_tier1_execution(self, mock_tier1, mock_tier2, mock_tier3):
        """Test that Tier 0 partial status allows Tier 1 to run (warning, not fail)."""
        from core.verifier import Verifier

        # Mock Tier 0 partial, but Tier 1, 2, 3 passing
        with patch.object(Verifier, "run_tier0_checklist") as mock_tier0:
            mock_tier0.return_value = {
                "status": "partial",
                "items_checked": 5,
                "items_passed": 3,
                "findings": ["✓ Some items passed", "✗ Some items failed"],
            }

            mock_tier1.return_value.run_tests.return_value = {
                "status": "pass",
                "evidence": "2 passed",
                "command": "pytest tests/test_arch.py -v",
            }
            mock_tier2.return_value.check_integration.return_value = {
                "status": "pass",
                "evidence": "Hook registered",
            }
            mock_tier3.return_value.check_e2e.return_value = {
                "status": "pass",
                "evidence": "Skill invoked",
            }

            verifier = Verifier()
            report = verifier.verify("skill:arch")

            # Tier 0 should be in report with partial status
            assert "tier0" in report
            assert report["tier0"]["status"] == "partial"

            # Tier 1, 2, 3 should still run
            mock_tier1.return_value.run_tests.assert_called_once()
            mock_tier2.return_value.check_integration.assert_called_once()
            mock_tier3.return_value.check_e2e.assert_called_once()

            # Overall status: tier0 partial doesn't trigger "verified" status
            # but tiers 1-3 should still run
            assert report["overall_status"] == "failed"

    @patch("core.verifier.Tier3E2E")
    @patch("core.verifier.Tier2Integration")
    @patch("core.verifier.Tier1Component")
    def test_tier0_pass_proceeds_to_tier1(self, mock_tier1, mock_tier2, mock_tier3):
        """Test that Tier 0 pass allows normal workflow to Tier 1."""
        from core.verifier import Verifier

        # Mock all tiers passing
        with patch.object(Verifier, "run_tier0_checklist") as mock_tier0:
            mock_tier0.return_value = {
                "status": "pass",
                "items_checked": 5,
                "items_passed": 5,
                "findings": ["✓ All checklist items passed"],
            }

            mock_tier1.return_value.run_tests.return_value = {
                "status": "pass",
                "evidence": "2 passed",
                "command": "pytest tests/test_arch.py -v",
            }
            mock_tier2.return_value.check_integration.return_value = {
                "status": "pass",
                "evidence": "Hook registered",
            }
            mock_tier3.return_value.check_e2e.return_value = {
                "status": "pass",
                "evidence": "Skill invoked",
            }

            verifier = Verifier()
            report = verifier.verify("skill:arch")

            # All tiers should be in report
            assert "tier0" in report
            assert "tier1" in report
            assert "tier2" in report
            assert "tier3" in report

            # All should pass
            assert report["tier0"]["status"] == "pass"
            assert report["tier1"]["status"] == "pass"
            assert report["tier2"]["status"] == "pass"
            assert report["tier3"]["status"] == "pass"

            # Overall should be verified
            assert report["overall_status"] == "verified"

            # Verify execution order: Tier 0 → Tier 1 → Tier 2 → Tier 3
            assert mock_tier0.call_count == 1
            assert mock_tier1.return_value.run_tests.call_count == 1
            assert mock_tier2.return_value.check_integration.call_count == 1
            assert mock_tier3.return_value.check_e2e.call_count == 1


class TestTier0ReportStructure:
    """Test that Tier 0 results are properly included in verification report."""

    @patch("core.verifier.Tier3E2E")
    @patch("core.verifier.Tier2Integration")
    @patch("core.verifier.Tier1Component")
    def test_report_includes_tier0_results(self, mock_tier1, mock_tier2, mock_tier3):
        """Test that verification report includes Tier 0 results."""
        from core.verifier import Verifier

        with patch.object(Verifier, "run_tier0_checklist") as mock_tier0:
            mock_tier0.return_value = {
                "status": "pass",
                "items_checked": 5,
                "items_passed": 5,
                "findings": ["✓ Item 1", "✓ Item 2", "✓ Item 3", "✓ Item 4", "✓ Item 5"],
            }

            mock_tier1.return_value.run_tests.return_value = {
                "status": "pass",
                "evidence": "2 passed",
                "command": "pytest tests/test_arch.py -v",
            }
            mock_tier2.return_value.check_integration.return_value = {
                "status": "pass",
                "evidence": "Hook registered",
            }
            mock_tier3.return_value.check_e2e.return_value = {
                "status": "pass",
                "evidence": "Skill invoked",
            }

            verifier = Verifier()
            report = verifier.verify("skill:arch")

            # Verify Tier 0 structure in report
            assert "tier0" in report
            assert "status" in report["tier0"]
            assert "items_checked" in report["tier0"]
            assert "items_passed" in report["tier0"]
            assert "findings" in report["tier0"]

            # Verify values
            assert report["tier0"]["status"] == "pass"
            assert report["tier0"]["items_checked"] == 5
            assert report["tier0"]["items_passed"] == 5
            assert len(report["tier0"]["findings"]) == 5

    @patch("core.verifier.Tier3E2E")
    @patch("core.verifier.Tier2Integration")
    @patch("core.verifier.Tier1Component")
    def test_report_preserves_tier0_findings(self, mock_tier1, mock_tier2, mock_tier3):
        """Test that Tier 0 findings are preserved in report."""
        from core.verifier import Verifier

        expected_findings = [
            "✓ SKILL.md exists at .claude/skills/arch/SKILL.md",
            "✓ Has required name field",
            "✓ Has required description field",
            "✗ Missing triggers field",
            "✓ Has workflow_steps defined",
        ]

        with patch.object(Verifier, "run_tier0_checklist") as mock_tier0:
            mock_tier0.return_value = {
                "status": "partial",
                "items_checked": 5,
                "items_passed": 4,
                "findings": expected_findings,
            }

            mock_tier1.return_value.run_tests.return_value = {
                "status": "pass",
                "evidence": "2 passed",
                "command": "pytest tests/test_arch.py -v",
            }
            mock_tier2.return_value.check_integration.return_value = {
                "status": "pass",
                "evidence": "Hook registered",
            }
            mock_tier3.return_value.check_e2e.return_value = {
                "status": "pass",
                "evidence": "Skill invoked",
            }

            verifier = Verifier()
            report = verifier.verify("skill:arch")

            # Verify findings are preserved exactly
            assert report["tier0"]["findings"] == expected_findings

    @patch("core.verifier.Tier3E2E")
    @patch("core.verifier.Tier2Integration")
    @patch("core.verifier.Tier1Component")
    def test_report_includes_all_tier_results(self, mock_tier1, mock_tier2, mock_tier3):
        """Test that report includes all 4 tiers (0, 1, 2, 3)."""
        from core.verifier import Verifier

        with patch.object(Verifier, "run_tier0_checklist") as mock_tier0:
            mock_tier0.return_value = {
                "status": "pass",
                "items_checked": 5,
                "items_passed": 5,
                "findings": ["✓ All passed"],
            }

            mock_tier1.return_value.run_tests.return_value = {
                "status": "pass",
                "evidence": "Tests passed",
                "command": "pytest tests/test_arch.py -v",
            }
            mock_tier2.return_value.check_integration.return_value = {
                "status": "pass",
                "evidence": "Integration OK",
            }
            mock_tier3.return_value.check_e2e.return_value = {
                "status": "pass",
                "evidence": "E2E OK",
            }

            verifier = Verifier()
            report = verifier.verify("skill:arch")

            # Verify all 4 tiers are present
            assert "tier0" in report
            assert "tier1" in report
            assert "tier2" in report
            assert "tier3" in report

            # Verify all have status
            for tier_num in ["tier0", "tier1", "tier2", "tier3"]:
                assert "status" in report[tier_num]
                assert report[tier_num]["status"] == "pass"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
